/* ============================================================
   Calculia — Textos de monedero (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "💶 The Coin Purse",
    "instruction": "Here you practise real money: counting it, paying, checking the change and saving.",
    "backToMenu": "← Menu",
    "chooseLevel": "Choose a step",
    "btnAnotherLevel": "Choose another step",
    "menuCount": "How much is there?",
    "menuCountDetail": "Look at the money and choose the total.",
    "menuPay": "Pay the exact price",
    "menuPayDetail": "Touch the money up to the exact price.",
    "menuPayWith": "What do I pay with?",
    "menuPayWithDetail": "Choose the money that is enough.",
    "menuCheckChange": "Is the change right?",
    "menuCheckChangeDetail": "Count the change and decide.",
    "menuPiggyBank": "The Piggy Bank",
    "menuPiggyBankDetail": "How much is missing to buy it?",
    "menuRounding": "More or less",
    "menuRoundingDetail": "How much is it, without counting cents?",
    "instructionCount": "How much money is there? Count the money and choose the total.",
    "instructionPayWith": "You do not have the exact price. Choose the money that is enough to pay.",
    "instructionCheckChange": "You have paid. Count the change and decide if it is right.",
    "instructionPiggyBank": "You want to buy something. Count your money and work out how much is missing.",
    "instructionRounding": "Look at the price. Say how much it is, more or less, without counting the cents.",
    "addMoney": "Add {d}",
    "countPrompt": "How much money is there?",
    "tableAria": "Money on the table",
    "listenHintAria": "Listen to the help",
    "countHint": "Count again, slowly. Start with the biggest money.",
    "correctExplanation": "That is it! There is {d}. In total, {total}.",
    "almostExplanation": "Look: there is {d}. In total, {total}.",
    "countSummary": "You counted correctly {n} out of {t}.",
    "payWithPrompt": "{nombre} costs {precio}. You do not have the exact price. What do you pay with?",
    "payWithHint": "Look at the price. Is that money more or less than the price?",
    "payCorrectExplanation": "That is it! You pay with {pagado}. You get {cambio} back.",
    "payAlmostExplanation": "Look: that money is less than the price. You pay with {pagado}. You get {cambio} back.",
    "changeBack": "You get back:",
    "payWithSummary": "You paid right first time {n} out of {t}.",
    "changePrompt": "It costs {precio}. You pay with {pagado}. You get this back. Is the change right?",
    "answerYes": "Yes",
    "answerNo": "No",
    "changeHint": "Count the money on the table. How much did you get back?",
    "changeCorrectExplanation": "The right change is {bueno}. You got {mostrado}. It is right!",
    "changeShortExplanation": "The right change is {bueno}. You got {mostrado}. It is wrong: money is missing.",
    "changeOverExplanation": "The right change is {bueno}. You got {mostrado}. It is wrong: you got too much.",
    "changeSummary": "You checked correctly {n} out of {t}.",
    "piggyBankPrompt": "You want to buy {nombre}. It costs {precio}. You have this money. How much is missing?",
    "piggyBankHint": "First count the money on the table. Then look at the price.",
    "piggyBankCorrectExplanation": "That is it! It costs {precio}. You have {tienes}. {falta} is missing.",
    "piggyBankAlmostExplanation": "Look: it costs {precio}. You have {tienes}. {falta} is missing.",
    "piggyBankSummary": "You worked it out correctly {n} out of {t}.",
    "roundingPrompt": "{nombre} costs {precio}. How much is that, more or less?",
    "aboutEuros": "about {n} €",
    "roundingHint": "Look at the cents. Are they closer to the euro above or the euro below?",
    "roundingCorrectExplanation": "That is it! {precio} is very close to {n} €. We say: about {n} €.",
    "roundingAlmostExplanation": "Look: {precio} is very close to {n} €. We say: about {n} €.",
    "roundingHalfCorrectExplanation": "That is it! {precio} ends in 50. When it ends in 50, we say the euro above: about {n} €.",
    "roundingHalfAlmostExplanation": "Look: {precio} ends in 50. When it ends in 50, we say the euro above: about {n} €.",
    "roundingSummary": "You estimated correctly {n} out of {t}.",
    "payInstruction": "Look at the price. Touch the money until you reach the exact price.",
    "placed": "You have put in: {total}",
    "removeLast": "↩ Remove last",
    "clear": "🗑 Empty",
    "check": "Check",
    "costs": "{nombre}: {precio}",
    "missingMoney1": "Not enough money. Look at the price and look at what you have put in.",
    "tooMuchMoney1": "Too much money. Look at the price and look at what you have put in.",
    "missingMoney2": "{dif} missing. Add more money.",
    "tooMuchMoney2": "{dif} too much. Remove some money.",
    "paySummary": "You paid the exact price first time {n} out of {t}.",
    "btnHint": "💡 Help",
    "payHint1": "Look at the price and look at your total. What is the biggest money that fits without going over?",
    "payHint2": "Touch the marked money: it fits without going over the price.",
    "removeHint1": "Look at your total. Have you put in more money than the price?",
    "removeHint2": "Touch the marked button to remove money.",
    "checkHint": "Your total equals the price. Touch Check!",
  "contexto": "You have money on the table. You will count it, pay, check the change and save for something you want.",
  "pista": "🤔 Count the money slowly. How much is there altogether?",
  "explicacion": "✅ That is how to use money. Next time you have coins, try counting them like this.",
  "transfer": "This will help you handle real money: count it, pay, check the change and save.",
  }, 'en');
})();
