/* ============================================================
   Calculia — Textos de monedero (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "💶 The Coin Purse",
    "instruccion": "Here you practise real money: counting it, paying, checking the change and saving.",
    "volverMenu": "← Menu",
    "elegirNivel": "Choose a step",
    "btnOtroNivel": "Choose another step",
    "menuContar": "How much is there?",
    "menuContarDetalle": "Look at the money and choose the total.",
    "menuPagar": "Pay the exact price",
    "menuPagarDetalle": "Touch the money up to the exact price.",
    "menuConQuePago": "What do I pay with?",
    "menuConQuePagoDetalle": "Choose the money that is enough.",
    "menuCambio": "Is the change right?",
    "menuCambioDetalle": "Count the change and decide.",
    "menuHucha": "The Piggy Bank",
    "menuHuchaDetalle": "How much is missing to buy it?",
    "menuRedondeo": "More or less",
    "menuRedondeoDetalle": "How much is it, without counting cents?",
    "instruccionContar": "How much money is there? Count the money and choose the total.",
    "instruccionConQuePago": "You do not have the exact price. Choose the money that is enough to pay.",
    "instruccionCambio": "You have paid. Count the change and decide if it is right.",
    "instruccionHucha": "You want to buy something. Count your money and work out how much is missing.",
    "instruccionRedondeo": "Look at the price. Say how much it is, more or less, without counting the cents.",
    "anadirDinero": "Add {d}",
    "contarPregunta": "How much money is there?",
    "ariaMesa": "Money on the table",
    "ariaEscucharAyuda": "Listen to the help",
    "pistaContar": "Count again, slowly. Start with the biggest money.",
    "explicacionBien": "That is it! There is {d}. In total, {total}.",
    "explicacionCasi": "Look: there is {d}. In total, {total}.",
    "resumenContar": "You counted correctly {n} out of {t}.",
    "enunciadoConQuePago": "{nombre} costs {precio}. You do not have the exact price. What do you pay with?",
    "pistaConQuePago": "Look at the price. Is that money more or less than the price?",
    "explicacionPagoBien": "That is it! You pay with {pagado}. You get {cambio} back.",
    "explicacionPagoCasi": "Look: that money is less than the price. You pay with {pagado}. You get {cambio} back.",
    "teDevuelven": "You get back:",
    "resumenConQuePago": "You paid right first time {n} out of {t}.",
    "enunciadoCambio": "It costs {precio}. You pay with {pagado}. You get this back. Is the change right?",
    "si": "Yes",
    "no": "No",
    "pistaCambio": "Count the money on the table. How much did you get back?",
    "explicacionCambioBien": "The right change is {bueno}. You got {mostrado}. It is right!",
    "explicacionCambioFalta": "The right change is {bueno}. You got {mostrado}. It is wrong: money is missing.",
    "explicacionCambioSobra": "The right change is {bueno}. You got {mostrado}. It is wrong: you got too much.",
    "resumenCambio": "You checked correctly {n} out of {t}.",
    "enunciadoHucha": "You want to buy {nombre}. It costs {precio}. You have this money. How much is missing?",
    "pistaHucha": "First count the money on the table. Then look at the price.",
    "explicacionHuchaBien": "That is it! It costs {precio}. You have {tienes}. {falta} is missing.",
    "explicacionHuchaCasi": "Look: it costs {precio}. You have {tienes}. {falta} is missing.",
    "resumenHucha": "You worked it out correctly {n} out of {t}.",
    "enunciadoRedondeo": "{nombre} costs {precio}. How much is that, more or less?",
    "unosEuros": "about {n} €",
    "pistaRedondeo": "Look at the cents. Are they closer to the euro above or the euro below?",
    "explicacionRedondeoBien": "That is it! {precio} is very close to {n} €. We say: about {n} €.",
    "explicacionRedondeoCasi": "Look: {precio} is very close to {n} €. We say: about {n} €.",
    "explicacionRedondeoMedioBien": "That is it! {precio} ends in 50. When it ends in 50, we say the euro above: about {n} €.",
    "explicacionRedondeoMedioCasi": "Look: {precio} ends in 50. When it ends in 50, we say the euro above: about {n} €.",
    "resumenRedondeo": "You estimated correctly {n} out of {t}.",
    "pagarInstruccion": "Look at the price. Touch the money until you reach the exact price.",
    "hasPuesto": "You have put in: {total}",
    "quitarUltima": "↩ Remove last",
    "vaciar": "🗑 Empty",
    "comprobar": "Check",
    "cuesta": "{nombre}: {precio}",
    "faltaDinero1": "Not enough money. Look at the price and look at what you have put in.",
    "sobraDinero1": "Too much money. Look at the price and look at what you have put in.",
    "faltaDinero2": "{dif} missing. Add more money.",
    "sobraDinero2": "{dif} too much. Remove some money.",
    "resumenPagar": "You paid the exact price first time {n} out of {t}.",
    "btnAyuda": "💡 Help",
    "ayudaPagar1": "Look at the price and look at your total. What is the biggest money that fits without going over?",
    "ayudaPagar2": "Touch the marked money: it fits without going over the price.",
    "ayudaQuita1": "Look at your total. Have you put in more money than the price?",
    "ayudaQuita2": "Touch the marked button to remove money.",
    "ayudaComprobar": "Your total equals the price. Touch Check!",
  "contexto": "You have money on the table. You will count it, pay, check the change and save for something you want.",
  "pista": "🤔 Count the money slowly. How much is there altogether?",
  "explicacion": "✅ That is how to use money. Next time you have coins, try counting them like this.",
  "transferencia": "This will help you handle real money: count it, pay, check the change and save.",
  }, 'en');
})();
