/* ============================================================
   Calculia — Textos de monedero (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "💶 El Monedero",
    "instruction": "Aquí practicas el dinero de verdad: contarlo, pagar, comprobar el cambio y ahorrar.",
    "backToMenu": "← Menú",
    "chooseLevel": "Elige un paso",
    "btnAnotherLevel": "Elegir otro paso",
    "menuCount": "¿Cuánto hay?",
    "menuCountDetail": "Mira el dinero y elige el total.",
    "menuPay": "Paga justo",
    "menuPayDetail": "Toca el dinero hasta el precio exacto.",
    "menuPayWith": "¿Con qué pago?",
    "menuPayWithDetail": "Elige el dinero que llega.",
    "menuCheckChange": "¿Está bien el cambio?",
    "menuCheckChangeDetail": "Cuenta el cambio y decide.",
    "menuPiggyBank": "La Hucha",
    "menuPiggyBankDetail": "¿Cuánto te falta para comprarlo?",
    "menuRounding": "Más o menos",
    "menuRoundingDetail": "¿Cuánto es, sin contar céntimos?",
    "instructionCount": "¿Cuánto dinero hay? Cuenta el dinero y elige el total.",
    "instructionPayWith": "No tienes el precio justo. Elige el dinero que llega para pagar.",
    "instructionCheckChange": "Has pagado. Cuenta el cambio y decide si está bien.",
    "instructionPiggyBank": "Quieres comprar algo. Cuenta tu dinero y calcula cuánto te falta.",
    "instructionRounding": "Mira el precio. Di cuánto es, más o menos, sin contar los céntimos.",
    "addMoney": "Añadir {d}",
    "countPrompt": "¿Cuánto dinero hay?",
    "tableAria": "Dinero sobre la mesa",
    "listenHintAria": "Escuchar la ayuda",
    "countHint": "Cuenta otra vez, despacio. Empieza por el dinero más grande.",
    "correctExplanation": "¡Eso es! Hay {d}. En total, {total}.",
    "almostExplanation": "Mira: hay {d}. En total, {total}.",
    "countSummary": "Has contado bien {n} de {t}.",
    "payWithPrompt": "{nombre} cuesta {precio}. No tienes el precio justo. ¿Con qué pagas?",
    "payWithHint": "Mira el precio. ¿Ese dinero es más o menos que el precio?",
    "payCorrectExplanation": "¡Eso es! Pagas con {pagado}. Te devuelven {cambio}.",
    "payAlmostExplanation": "Mira: ese dinero es menos que el precio. Se paga con {pagado}. Te devuelven {cambio}.",
    "changeBack": "Te devuelven:",
    "payWithSummary": "Has pagado bien a la primera {n} de {t}.",
    "changePrompt": "Cuesta {precio}. Pagas con {pagado}. Te devuelven esto. ¿Está bien el cambio?",
    "answerYes": "Sí",
    "answerNo": "No",
    "changeHint": "Cuenta el dinero de la mesa. ¿Cuánto te han devuelto?",
    "changeCorrectExplanation": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. ¡Está bien!",
    "changeShortExplanation": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal: te falta dinero.",
    "changeOverExplanation": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal: te han dado de más.",
    "changeSummary": "Has comprobado bien {n} de {t}.",
    "piggyBankPrompt": "Quieres comprar {nombre}. Cuesta {precio}. Tienes este dinero. ¿Cuánto te falta?",
    "piggyBankHint": "Cuenta primero el dinero de la mesa. Después mira el precio.",
    "piggyBankCorrectExplanation": "¡Eso es! Cuesta {precio}. Tienes {tienes}. Te faltan {falta}.",
    "piggyBankAlmostExplanation": "Mira: cuesta {precio}. Tienes {tienes}. Te faltan {falta}.",
    "piggyBankSummary": "Has calculado bien {n} de {t}.",
    "roundingPrompt": "{nombre} cuesta {precio}. ¿Cuánto es, más o menos?",
    "aboutEuros": "unos {n} €",
    "roundingHint": "Mira los céntimos. ¿Están más cerca del euro de arriba o del euro de abajo?",
    "roundingCorrectExplanation": "¡Eso es! {precio} está muy cerca de {n} €. Decimos: unos {n} €.",
    "roundingAlmostExplanation": "Mira: {precio} está muy cerca de {n} €. Decimos: unos {n} €.",
    "roundingHalfCorrectExplanation": "¡Eso es! {precio} acaba en 50. Cuando acaba en 50, decimos el euro de arriba: unos {n} €.",
    "roundingHalfAlmostExplanation": "Mira: {precio} acaba en 50. Cuando acaba en 50, decimos el euro de arriba: unos {n} €.",
    "roundingSummary": "Has estimado bien {n} de {t}.",
    "payInstruction": "Mira el precio. Toca el dinero hasta llegar al precio justo.",
    "placed": "Has puesto: {total}",
    "removeLast": "↩ Quitar última",
    "clear": "🗑 Vaciar",
    "check": "Comprobar",
    "costs": "{nombre}: {precio}",
    "missingMoney1": "Falta dinero. Mira el precio y mira lo que has puesto.",
    "tooMuchMoney1": "Sobra dinero. Mira el precio y mira lo que has puesto.",
    "missingMoney2": "Faltan {dif}. Añade más dinero.",
    "tooMuchMoney2": "Sobran {dif}. Quita algún dinero.",
    "paySummary": "Has pagado justo a la primera {n} de {t}.",
    "btnHint": "💡 Ayuda",
    "payHint1": "Mira el precio y mira tu total. ¿Cuál es el dinero más grande que cabe sin pasarte?",
    "payHint2": "Toca el dinero marcado: cabe sin pasarte del precio.",
    "removeHint1": "Mira tu total. ¿Has puesto más dinero que el precio?",
    "removeHint2": "Toca el botón marcado para quitar dinero.",
    "checkHint": "Tu total es igual al precio. ¡Toca Comprobar!",
  "contexto": "Tienes dinero en la mesa. Vas a contarlo, pagar, comprobar el cambio y ahorrar para algo que quieres.",
  "pista": "🤔 Cuenta el dinero despacio. ¿Cuánto hay en total?",
  "explicacion": "✅ Así se usa el dinero. La próxima vez que tengas monedas, prueba a contarlas así.",
  "transfer": "Esto te servirá para manejarte con dinero de verdad: contar, pagar, comprobar el cambio y ahorrar.",
  }, 'es');
})();
