/* ============================================================
   Apptonomia — Textos de monedero (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "💶 El Monedero",
    "instruccion": "Aquí practicas el dinero de verdad: contarlo, pagar, comprobar el cambio y ahorrar.",
    "volverMenu": "← Menú",
    "elegirNivel": "Elige el nivel",
    "vecesTexto": "{n} veces",
    "btnOtroNivel": "Elegir otro nivel",
    "menuContar": "¿Cuánto hay?",
    "menuContarDetalle": "Mira el dinero y elige el total.",
    "menuPagar": "Paga justo",
    "menuPagarDetalle": "Toca el dinero hasta el precio exacto.",
    "menuConQuePago": "¿Con qué pago?",
    "menuConQuePagoDetalle": "Elige el dinero que llega.",
    "menuCambio": "¿Está bien el cambio?",
    "menuCambioDetalle": "Cuenta el cambio y decide.",
    "menuHucha": "La Hucha",
    "menuHuchaDetalle": "¿Cuánto te falta para comprarlo?",
    "menuRedondeo": "Más o menos",
    "menuRedondeoDetalle": "¿Cuánto es, sin contar céntimos?",
    "instruccionContar": "¿Cuánto dinero hay? Cuenta el dinero y elige el total.",
    "instruccionConQuePago": "No tienes el precio justo. Elige el dinero que llega para pagar.",
    "instruccionCambio": "Has pagado. Cuenta el cambio y decide si está bien.",
    "instruccionHucha": "Quieres comprar algo. Cuenta tu dinero y calcula cuánto te falta.",
    "instruccionRedondeo": "Mira el precio. Di cuánto es, más o menos, sin contar los céntimos.",
    "anadirDinero": "Añadir {d}",
    "contarPregunta": "¿Cuánto dinero hay?",
    "contarEnunciadoAudio": "En la mesa hay: {d}. ¿Cuánto dinero hay en total?",
    "ariaMesa": "Dinero sobre la mesa",
    "pistaContar": "Cuenta otra vez, despacio. Empieza por el dinero más grande.",
    "explicacionBien": "¡Eso es! Hay {d}. En total, {total}.",
    "explicacionCasi": "Mira: hay {d}. En total, {total}.",
    "resumenContar": "Has contado bien {n} de {t}.",
    "enunciadoConQuePago": "{nombre} cuesta {precio}. No tienes el precio justo. ¿Con qué pagas?",
    "pistaConQuePago": "Mira el precio. ¿Ese dinero es más o menos que el precio?",
    "explicacionPagoBien": "¡Eso es! Pagas con {pagado}. Te devuelven {cambio}.",
    "explicacionPagoCasi": "Mira: ese dinero es menos que el precio. Se paga con {pagado}. Te devuelven {cambio}.",
    "teDevuelven": "Te devuelven:",
    "resumenConQuePago": "Has pagado bien a la primera {n} de {t}.",
    "enunciadoCambio": "Cuesta {precio}. Pagas con {pagado}. Te devuelven esto. ¿Está bien el cambio?",
    "si": "Sí",
    "no": "No",
    "pistaCambio": "Cuenta el dinero de la mesa. ¿Cuánto te han devuelto?",
    "explicacionCambioBien": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. ¡Está bien!",
    "explicacionCambioFalta": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal: te falta dinero.",
    "explicacionCambioSobra": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal: te han dado de más.",
    "resumenCambio": "Has comprobado bien {n} de {t}.",
    "enunciadoHucha": "Quieres comprar {nombre}. Cuesta {precio}. Tienes este dinero. ¿Cuánto te falta?",
    "pistaHucha": "Cuenta primero el dinero de la mesa. Después mira el precio.",
    "explicacionHuchaBien": "¡Eso es! Cuesta {precio}. Tienes {tienes}. Te faltan {falta}.",
    "explicacionHuchaCasi": "Mira: cuesta {precio}. Tienes {tienes}. Te faltan {falta}.",
    "resumenHucha": "Has calculado bien {n} de {t}.",
    "enunciadoRedondeo": "{nombre} cuesta {precio}. ¿Cuánto es, más o menos?",
    "unosEuros": "unos {n} €",
    "pistaRedondeo": "Mira los céntimos. ¿Están más cerca del euro de arriba o del euro de abajo?",
    "explicacionRedondeoBien": "¡Eso es! {precio} está muy cerca de {n} €. Decimos: unos {n} €.",
    "explicacionRedondeoCasi": "Mira: {precio} está muy cerca de {n} €. Decimos: unos {n} €.",
    "explicacionRedondeoMedioBien": "¡Eso es! {precio} acaba en 50. Cuando acaba en 50, decimos el euro de arriba: unos {n} €.",
    "explicacionRedondeoMedioCasi": "Mira: {precio} acaba en 50. Cuando acaba en 50, decimos el euro de arriba: unos {n} €.",
    "resumenRedondeo": "Has estimado bien {n} de {t}.",
    "pagarInstruccion": "Mira el precio. Toca el dinero hasta llegar al precio justo.",
    "hasPuesto": "Has puesto: {total}",
    "quitarUltima": "↩ Quitar última",
    "vaciar": "🗑 Vaciar",
    "comprobar": "Comprobar",
    "escucharPrecio": "Escuchar el precio",
    "cuesta": "{nombre}: {precio}",
    "faltaDinero1": "Falta dinero. Mira el precio y mira lo que has puesto.",
    "sobraDinero1": "Sobra dinero. Mira el precio y mira lo que has puesto.",
    "faltaDinero2": "Faltan {dif}. Añade más dinero.",
    "sobraDinero2": "Sobran {dif}. Quita algún dinero.",
    "resumenPagar": "Has pagado justo a la primera {n} de {t}.",
    "btnAyuda": "💡 Ayuda",
    "ariaEscucharAyuda": "Escuchar la ayuda",
    "ayudaPagar1": "Mira el precio y mira tu total. ¿Cuál es el dinero más grande que cabe sin pasarte?",
    "ayudaPagar2": "Toca el dinero marcado: cabe sin pasarte del precio.",
    "ayudaQuita1": "Mira tu total. ¿Has puesto más dinero que el precio?",
    "ayudaQuita2": "Toca el botón marcado para quitar dinero.",
    "ayudaComprobar": "Tu total es igual al precio. ¡Toca Comprobar!",
  "contexto": "Tienes dinero en la mesa. Vas a contarlo, pagar, comprobar el cambio y ahorrar para algo que quieres.",
  "pista": "🤔 Cuenta el dinero despacio. ¿Cuánto hay en total?",
  "explicacion": "✅ Así se usa el dinero. La próxima vez que tengas monedas, prueba a contarlas así.",
  "transferencia": "Esto te servirá para manejarte con dinero de verdad: contar, pagar, comprobar el cambio y ahorrar.",
  }, 'es');
})();
