(function () {
  'use strict';

  App.i18n.register({
    title: '🔢 Math Tables',
    instruction: 'Learn to count in your head, add and multiply with colored dots.',
    chooseOperation: 'Choose what you want to practise.',
    stepsName: 'Count in your head',
    stepsDetail: 'Add or subtract 1, 2, 3, 5 or 10 without using your fingers.',
    addName: 'Addition tables',
    addDetail: 'Join dots of two colors and count the total.',
    decomposeName: 'Break numbers apart',
    decomposeDetail: 'Make 10 first: 7 + 5 is 7 + 3 and 2 more.',
    multiplyName: 'Multiplication tables',
    multiplyDetail: 'Repeat groups of dots, each group in one color.',
    divideName: 'Divide by 10',
    divideDetail: 'Split the dots into rows of 10 and count the rows.',
    parityName: 'Even and odd',
    parityDetail: 'Count the dots two by two and classify the number.',
    parityPrompt: 'Is {a} even or odd?',
    evenLabel: 'Even',
    oddLabel: 'Odd',
    chooseTable: 'Choose a table.',
    chooseLevel: 'Choose a step.',
    tableButton: 'Table of {n}',
    stepLevel: 'Add and subtract {n}',
    tableTitleAdd: 'Addition table of {n}',
    tableTitleMultiply: 'Multiplication table of {n}',
    learnInstruction: 'Tap a row to see it with dots.',
    practiceTable: 'Practise this table',
    backToTables: '← Choose another table',
    backToLevels: '← Choose another step',
    progress: '{current} of {total}',
    hintAdd: 'Hint: count all the dots, one by one.',
    hintMultiply: 'Hint: there are {b} groups of {a} dots. Count group by group.',
    hintStepsAdd: 'Hint: start at {a} and count {b} more, one at a time.',
    hintStepsSubtract: 'Hint: start at {a} and count {b} backwards.',
    hintStepsAddRow: 'Hint: count in {b}s, like the rows.',
    hintStepsSubtractRow: 'Hint: take away one row of {b} and count what is left.',
    hintDecompose: 'Hint: from {a} to 10 you need {toTen}. Make 10 first.',
    hintDivide: 'Hint: each row has 10 dots. Count the rows.',
    hintParity: 'Hint: count the dots two by two. If one is left over, it is odd.',
    explainAdd: '{a} blue dots and {b} orange dots make {result} dots in total.',
    explainMultiply: '{b} groups of {a} dots make {result} dots in total.',
    explainStepsAdd: '{a} and {b} more make {result}.',
    explainStepsSubtract: '{a} minus {b} is {result}. The crossed-out dots no longer count.',
    explainStepsAddRow: '{a} and one more row of {b} make {result}.',
    explainStepsSubtractRow: '{a} minus one row of {b} makes {result}.',
    explainDecompose: '{a} + {b} is the same as {a} + {toTen} + {rest}. First 10, then {rest} more: {result}.',
    explainDivide: '{a} dots make {result} rows of 10. {a} ÷ 10 = {result}.',
    explainParity: 'Count the dots two by two: if none are left over, {a} is even. If one is left over, it is odd.',
    visualAdd: '{a} dots of one color and {b} dots of another color',
    visualMultiply: '{b} groups of {a} dots, each group in one color',
    visualStepsAdd: '{a} dots of one color and {b} dots of another color',
    visualStepsSubtract: '{a} dots, {b} of them crossed out',
    visualStepsAddRow: '{a} dots in rows of {b} and one more row of {b}',
    visualStepsSubtractRow: '{a} dots in rows of {b}, with the last row crossed out',
    visualDecompose: '{a} dots of one color, {toTen} of another to make 10 and {rest} more',
    visualDivide: '{a} dots split into rows of 10',
    visualParity: '{a} dots grouped two by two',
    roundSummary: 'You solved {count} operations. Now you have {stars} stars.',
    chooseAnotherTable: 'Choose another table',
    chooseAnotherLevel: 'Choose another step',
    changeOperation: 'Change activity',
    "contexto": "You are doing sums in your head. You will add, subtract, multiply or divide with visual help.",
    "pista": "🤔 Count the dots slowly. How many are there in total?",
    "explicacion": "✅ That is how to count in your head. Next time you add or subtract, try with fingers or dots.",
    "transferencia": "This will help you with everyday sums: at the shop, sharing things out, counting change or at school."
  }, 'en');
})();
