(function () {
  'use strict';

  App.i18n.register({
    title: '🔢 Las Tablas',
    instruction: 'Aprende a contar de cabeza, sumar y multiplicar con puntos de colores.',
    chooseOperation: 'Elige qué quieres practicar.',
    stepsName: 'Contar de cabeza',
    stepsDetail: 'Suma o resta 1, 2, 3, 5 o 10 sin usar los dedos.',
    addName: 'Tablas de sumar',
    addDetail: 'Junta puntos de dos colores y cuenta el total.',
    decomposeName: 'Descomponer números',
    decomposeDetail: 'Llega primero a 10: 7 + 5 es 7 + 3 y 2 más.',
    multiplyName: 'Tablas de multiplicar',
    multiplyDetail: 'Repite grupos de puntos, cada grupo de un color.',
    divideName: 'Dividir entre 10',
    divideDetail: 'Reparte los puntos en filas de 10 y cuenta las filas.',
    chooseTable: 'Elige una tabla.',
    chooseLevel: 'Elige un nivel.',
    tableButton: 'Tabla del {n}',
    stepLevel: 'Sumar y restar {n}',
    tableTitleAdd: 'Tabla de sumar del {n}',
    tableTitleMultiply: 'Tabla de multiplicar del {n}',
    learnInstruction: 'Toca una fila para verla con puntos y escucharla.',
    practiceTable: 'Practicar esta tabla',
    backToTables: '← Elegir otra tabla',
    backToLevels: '← Elegir otro nivel',
    quizPrompt: '¿Cuánto es {a} {symbol} {b}?',
    progress: '{current} de {total}',
    hintAdd: 'Pista: cuenta todos los puntos, uno a uno.',
    hintMultiply: 'Pista: son {b} grupos de {a} puntos. Cuenta grupo a grupo.',
    hintStepsAdd: 'Pista: empieza en {a} y cuenta {b} más, de uno en uno.',
    hintStepsSubtract: 'Pista: empieza en {a} y cuenta {b} hacia atrás.',
    hintStepsAddRow: 'Pista: cuenta de {b} en {b}, como las filas.',
    hintStepsSubtractRow: 'Pista: quita una fila de {b} y cuenta lo que queda.',
    hintDecompose: 'Pista: de {a} a 10 faltan {toTen}. Llega primero a 10.',
    hintDivide: 'Pista: cada fila tiene 10 puntos. Cuenta las filas.',
    explainAdd: '{a} puntos azules y {b} puntos naranjas son {result} puntos en total.',
    explainMultiply: '{b} grupos de {a} puntos son {result} puntos en total.',
    explainStepsAdd: '{a} y {b} más son {result}.',
    explainStepsSubtract: '{a} menos {b} son {result}. Los puntos tachados ya no se cuentan.',
    explainStepsAddRow: '{a} y una fila más de {b} son {result}.',
    explainStepsSubtractRow: '{a} menos una fila de {b} son {result}.',
    explainDecompose: '{a} + {b} es lo mismo que {a} + {toTen} + {rest}. Primero 10, y {rest} más: {result}.',
    explainDivide: '{a} puntos hacen {result} filas de 10. {a} ÷ 10 = {result}.',
    speakAdd: '{a} más {b} son {result}',
    speakSubtract: '{a} menos {b} son {result}',
    speakMultiply: '{a} por {b} es {result}',
    speakDivide: '{a} entre {b} son {result}',
    addWord: 'más',
    subtractWord: 'menos',
    multiplyWord: 'por',
    divideWord: 'entre',
    visualAdd: '{a} puntos de un color y {b} puntos de otro color',
    visualMultiply: '{b} grupos de {a} puntos, cada grupo de un color',
    visualStepsAdd: '{a} puntos de un color y {b} puntos de otro color',
    visualStepsSubtract: '{a} puntos, con {b} tachados',
    visualStepsAddRow: '{a} puntos en filas de {b} y una fila más de {b}',
    visualStepsSubtractRow: '{a} puntos en filas de {b}, con la última fila tachada',
    visualDecompose: '{a} puntos de un color, {toTen} de otro para llegar a 10 y {rest} más',
    visualDivide: '{a} puntos repartidos en filas de 10',
    roundSummary: 'Has resuelto {count} operaciones. Ahora tienes {stars} estrellas.',
    chooseAnotherTable: 'Elegir otra tabla',
    chooseAnotherLevel: 'Elegir otro nivel',
    changeOperation: 'Cambiar de actividad',
  "contexto": "Estás haciendo cuentas de cabeza. Vas a sumar, restar, multiplicar o dividir con ayuda visual.",
  "pista": "🤔 Cuenta los puntos despacio. ¿Cuántos hay en total?",
  "explicacion": "✅ Así se cuenta de cabeza. La próxima vez que sumes o restes, prueba con los dedos o con puntos.",
  "transferencia": "Esto te servirá para las cuentas del día a día: en la compra, al repartir, al contar el cambio o en el cole.",
  }, 'es');
})();
