/* ============================================================
   Calculia — Textos de la Presentación del proyecto (ES)
   Language-specific file. Loaded conditionally from index.html
   based on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "pageTitle": 'Presentación del proyecto',
    "routeNotice": 'Esta página no se enlaza desde la aplicación. Solo se llega escribiendo la dirección.',
    "tagline": 'Una aplicación para la autonomía.',
    "lead1": 'Calculia es una ',
    "leadStrong": 'aplicación web de cálculo y razonamiento lógico',
    "lead2": ' pensada para que las personas con discapacidad intelectual practiquen por sí mismas habilidades matemáticas y lógicas, sin presión y con respeto a su privacidad.',
    "navOrigin": 'El origen',
    "navPrinciples": 'Los principios',
    "navTech": 'Cómo está hecha',
    "navAreas": 'Las áreas de trabajo',
    "navSiblings": 'Proyectos hermanos',
    "navAuthorship": 'Quiénes la hacen',
    "navCollaborate": 'Cómo ayudar',
    "originTitle": 'El origen',
    "originP1a": 'Calculia nace de una pregunta que se repite al final de cada sesión de terapia ocupacional: ',
    "originP1em": '¿qué pasa entre una sesión y la siguiente?',
    "originP2": 'La persona con discapacidad intelectual practica con su terapeuta en consulta, pero después está sola en casa, en el colegio o en su tiempo libre. Queríamos una herramienta que respetase esa autonomía, que diese seguridad a las familias y que sirviese a la terapeuta como complemento entre sesiones, no como sustituto.',
    "originP3": 'Esta aplicación es el resultado: 14 actividades autónomas, todas en Lectura Fácil, todas accesibles, todas pensadas para que la persona usuaria pueda usarlas a su propio ritmo.',
    "principlesTitle": 'Los principios que no negociamos',
    "principlesIntro": 'Estas ideas están escritas primero en el código y después en los textos. Si una decisión las rompe, esa decisión está mal.',
    "principleAutonomyTitle": '🤲 Autonomía real',
    "principleAutonomyText": 'La persona usuaria puede usar la aplicación sin un profesional al lado. Si necesita ayuda constante, algo no está bien resuelto.',
    "principleNoPressureTitle": '🚫 Sin presión',
    "principleNoPressureText": 'Nada de cronómetros, ni "game over", ni puntuaciones negativas. El error se responde con ánimo y se puede reintentar sin límite.',
    "principlePrivacyTitle": '🔒 Privacidad por defecto',
    "principlePrivacyText": 'Sin registro, sin cookies, sin analítica, sin cuentas. Todo el progreso se guarda únicamente en el dispositivo de la persona.',
    "principleEasyReadTitle": '📖 Lectura Fácil',
    "principleEasyReadText": 'Frases cortas, una idea por frase, vocabulario cotidiano. Cero tecnicismos en la interfaz que ve la persona usuaria.',
    "principleAccessibilityTitle": '♿ Accesibilidad universal',
    "principleAccessibilityText": 'Botones grandes, alto contraste, audio solo cuando la gamificación o el diseño de la actividad lo requiera (p. ej. escuchar lo escrito con el teclado, lectura de enunciados), navegación completa por teclado, y respeto al modo de pocas animaciones del sistema.',
    "principleSoberTechTitle": '🧱 Tecnología sobria',
    "principleSoberTechText": 'HTML, CSS y JavaScript sin frameworks. Funciona sin internet y se puede instalar como aplicación. Código abierto, en un repositorio público.',
    "techTitle": 'Cómo está hecha',
    "techIntro1": 'Calculia es una aplicación web instalable (PWA) compuesta por más de ',
    "techIntroStrong": '25 páginas HTML estáticas',
    "techIntro2": ': una landing, 14 actividades y rutas ocultas para familias, terapeutas y mantenimiento.',
    "techItem1Label": 'Sin servidor propio',
    "techItem1Text": 'es un conjunto de archivos servidos por un hosting estático. No hay backend, ni bases de datos, ni API propia.',
    "techItem2Label": 'Funciona sin conexión',
    "techItem2Text": 'una vez instalada, abre aunque no haya internet gracias al service worker y al caché local.',
    "techItem3Label": 'Persistencia solo en',
    "techItem3Text": 'el progreso (estrellas, niveles completados, registro de emociones) vive en el navegador del dispositivo. Nunca se envía a ningún sitio.',
    "techItem4Label": 'Sin frameworks ni build step',
    "techItem4Text1": 'JavaScript clásico compatible con navegadores antiguos y con el protocolo',
    "techItem4Text2": '. Pensado para que un técnico novel pueda leer y modificar una actividad sin sorpresas.',
    "techItem5Label": 'Código abierto (licencia MIT)',
    "techItem5Text": 'cualquiera puede leerlo, auditarlo y proponer mejoras. Las decisiones de producto están escritas en este repositorio, no en presentaciones cerradas.',
    "techItem6Label": 'Internacionalización desde el inicio',
    "techItem6Text": 'cada texto vive en un archivo por idioma. Hoy Calculia está disponible en español de España e inglés.',
    "techItem7Label": 'Dependencias externas: ninguna',
    "techItem7Text": ', excepto la descarga de las fuentes tipográficas Atkinson Hyperlegible y Nunito (usadas por su alta legibilidad).',
    "areasTitle": 'Las áreas de trabajo',
    "areasIntro1": 'Las 14 actividades se agrupan en ',
    "areasIntroStrong": 'seis módulos de cálculo y razonamiento',
    "areasIntro2": ', cada uno con su color identificativo. Una actividad puede entrenar más de un área (por ejemplo, El Reloj mezcla lectura de la hora con razonamiento temporal), pero siempre aparece una sola vez en el menú, en su módulo principal.',
    "areaNumbersTitle": '🔢 Números y cantidades',
    "areaNumbersText": 'Reconocer números, comparar cantidades, contar, ordenar.',
    "areaNumbersCount": '3 actividades',
    "areaOperationsTitle": '➕ Cálculo mental y tablas',
    "areaOperationsText": 'Sumas, restas, tablas, partir una cuenta grande y los grupos exactos.',
    "areaOperationsCount": '5 actividades',
    "areaMeasuresTitle": '📏 Fracciones y medidas',
    "areaMeasuresText": 'Fracciones, medidas (longitud, peso) y temperatura.',
    "areaMeasuresCount": '3 actividades',
    "areaShapesTitle": '🔷 Formas, sitios y tamaños',
    "areaShapesText": 'Formas y cuerpos, situarse en el espacio, ángulos, bordes y simetría.',
    "areaShapesCount": '4 actividades',
    "areaProblemsTitle": '🤔 Problemas',
    "areaProblemsText": 'Entender lo que se cuenta y decidir qué hay que hacer.',
    "areaProblemsCount": '1 actividad',
    "areaChartsTitle": '📊 Datos y gráficos',
    "areaChartsText": 'Leer gráficos y tablas, repartir a partes iguales, el azar y las balanzas.',
    "areaChartsCount": '2 actividades',
    "areaReasoningTitle": '🧩 Razonamiento y lógica',
    "areaReasoningText": 'Series, patrones, adivinanzas y el "qué sobra".',
    "areaReasoningCount": '4 actividades',
    "areaMoneyTitle": '💶 Dinero y monedero',
    "areaMoneyText": 'Monedas y billetes, contar vueltas, el monedero y los porcentajes de las rebajas.',
    "areaMoneyCount": '3 actividades',
    "areaClockTitle": '⏰ El tiempo y los números romanos',
    "areaClockText": 'Leer la hora en analógico y digital, y reconocer números romanos.',
    "areaClockCount": '3 actividades',
    "areasNote1": 'Total: ',
    "areasNoteStrong": '14 actividades',
    "areasNote2": ', organizadas para que la persona elija por interés, no por obligación. El orden del menú no es un itinerario: cada persona hace su propio camino.',
    "siblingsTitle": 'Proyectos hermanos',
    "siblingsIntro": 'Calculia es uno más de un pequeño grupo de proyectos hermanos: mismo equipo, misma filosofía de accesibilidad y sin servidor propio. Cada uno es un servicio independiente, con su propio dominio, al que se puede llegar desde aquí.',
    "siblingRoutimeName": 'Routime',
    "siblingRoutimeText": 'Rutinas y autonomía del día a día.',
    "siblingMemofunName": 'Memofun',
    "siblingMemofunText": 'Memoria y atención.',
    "siblingOkeymoneyName": 'Okeymoney',
    "siblingOkeymoneyText": 'Finanzas personales y autonomía cotidiana.',
    "siblingSinonimiaName": 'Sinonimia',
    "siblingSinonimiaText": 'Diccionario en lectura fácil.',
    "siblingTeclatlonName": 'Teclatlon',
    "siblingTeclatlonText": 'Mecanografía con el teclado físico.',
    "siblingLinkHint": 'Se abre en una pestaña nueva.',
    "authorshipTitle": 'Quiénes la hacen',
    "authorshipP1a": 'Calculia es una iniciativa de ',
    "authorshipP1b": ', un estudio independiente que trabaja en proyectos abiertos con impacto social y educativo.',
    "authorshipP2": 'La aplicación se construye con la participación de personas con discapacidad intelectual, familias, terapeutas ocupacionales y profesorado, que prueban cada cambio y revisan el contenido antes de que llegue a producción.',
    "authorshipP3": 'El código, el texto y las decisiones se publican en abierto para que cualquier persona o equipo pueda auditarlos, aprender de ellos y adaptarlos a otros contextos.',
    "collaborateTitle": 'Cómo ayudar',
    "collaborateIntro": 'Calculia es un proyecto abierto. Hay formas de colaborar que no requieren programar:',
    "collaborateItem1Label": 'Probar y compartir feedback',
    "collaborateItem1Text": 'las familias, terapeutas y personas usuarias que prueban la aplicación y cuentan qué funciona y qué no, son la pieza clave del proyecto. Los errores de Lectura Fácil, los tonos poco amables y las actividades que cuesta entender se detectan usándolas.',
    "collaborateItem2Label": 'Proponer actividades',
    "collaborateItem2Text": 'si una habilidad de cálculo o razonamiento no está cubierta o se trabaja de una forma mejorable, se puede proponer una actividad nueva. La descripción didáctica la valida un profesional antes de pasar a código.',
    "collaborateItem3Label": 'Revisar contenido',
    "collaborateItem3Text": 'traducciones, ejemplos culturalmente adecuados, explicaciones accesibles. La interfaz que ve la persona usuaria es en Lectura Fácil y se beneficia especialmente de ojos ajenos.',
    "collaborateItem4Label": 'Contribuir código',
    "collaborateItem4Text": 'el repositorio es público. Cambios pequeños (un icono, una traducción, una corrección de estilo) y grandes (actividades nuevas, accesibilidad, soporte para más idiomas) se aceptan siempre que respeten los principios del proyecto.',
    "collaborateItem5Label": 'Difundir',
    "collaborateItem5Text": 'contar que existe. Muchas familias, profesionales y centros no saben que hay herramientas como esta hasta que alguien se la enseña.',
    "collaborateOutro1": 'Toda la documentación necesaria para empezar está en los archivos',
    "collaborateOutro3": 'y',
    "collaborateOutro4": 'del repositorio.',
    "footerActivities": 'Ir a las actividades'
  }, 'es');
})();
