/* ============================================================
   Calculia — Data and charts texts (EN)
   Locale-specific file. Same keys as strings.es.js.
   Loaded conditionally from index.html according to App.i18n.locale().
   Set and category names live in 'set.*' and 'cat.*': app.js looks
   them up by the id data.js uses, so adding a set means adding its id
   here and in both languages.
   The numbers are NOT here: they live once, in data.js.
   Short sentences, one idea per sentence (UNE 153101).
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '📊 Data and charts',
    instructionMenu: 'Choose an activity.',
    contexto: 'A chart tells you at a glance something that would take a long time in words. They turn up in the news, at the doctor and in the supermarket.',
    explicacion: '✅ Reading a chart means looking at it calmly and counting: which has most, which has least, and how many there are of each.',
    btnBackToMenu: '← Other activities',
    btnMenu: 'Back to start',
    otherLevel: 'Choose another level',
    endSummary: 'You solved {n} questions of {activity}. You now have {stars} stars.',
    btnHarder: 'Want to try «{name}»?',
    btnOtherActivity: 'Another activity',
    correctExplanation: '✅ Correct! The answer is: ',
    incorrectExplanationA: '❌ Look: the correct answer is ',
    hint: '🤔 Try again. Look at the chart calmly.',
    reinforceTitle: 'Reinforcement',
    reinforceIntro: "Let's repeat the {n} questions you missed until you get them all right.",
    reinforceDone: "Reinforcement done! You've got them all.",
    chance: {
      certain: 'Certain',
      possible: 'It might',
      impossible: 'Impossible'
    },
    set: {
      fruit: 'The fruit in the basket.',
      pets: 'The animals in the class.',
      weather: 'The weather these days.',
      transport: 'How people get here.',
      drinks: 'What has been drunk today.',
      books: 'Books read each day.',
      goals: 'Goals for each team.',
      visitors: 'People who came.',
      plants: 'Plants in each place.',
      sweets: 'The sweets each one has.',
      marbles: 'The marbles each one has.',
      cards: 'The cards each one has.',
      stickers: 'The stickers each one has.'
    },
    cat: {
      apple: 'apples',
      banana: 'bananas',
      orange: 'oranges',
      dog: 'dogs',
      cat: 'cats',
      fish: 'fish',
      sun: 'sunny days',
      rain: 'rainy days',
      cloud: 'cloudy days',
      bus: 'by bus',
      bike: 'by bike',
      walk: 'walking',
      water: 'water',
      milk: 'milk',
      juice: 'juice',
      monday: 'Monday',
      tuesday: 'Tuesday',
      wednesday: 'Wednesday',
      teamRed: 'the red team',
      teamBlue: 'the blue team',
      teamGreen: 'the green team',
      morning: 'in the morning',
      noon: 'at midday',
      evening: 'in the evening',
      garden: 'in the garden',
      balcony: 'on the balcony',
      window: 'on the window sill',
      ana: 'Ana',
      luis: 'Luis',
      sara: 'Sara',
      red: 'a red ball',
      blue: 'a blue ball',
      green: 'a green ball',
      yellow: 'a yellow ball'
    },
    activity: {
      dosCosas: { name: 'Two things at once', detail: 'Do they go together.', instruction: 'When two things are measured at the same time you can see whether they go together. Look at the cloud of dots from left to right: if the dots climb, when one goes up so does the other. If they fall, when one goes up the other goes down.' },
      despues: { name: 'And then', detail: 'What is left in the bag.', instruction: 'If you take a ball out and do not put it back, next time there is one fewer. The bag is drawn before and after: count what is left.' },
      combinaciones: { name: 'Combinations', detail: 'How many come out.', instruction: 'If you have several tops and several bottoms, you can dress in many different ways. All of them are drawn here: you only have to count them.' },
      reparto: { name: 'Together or spread out', detail: 'How far apart they are.', instruction: 'Two groups can have the same number of measurements and be very close together or very far apart. Look at how far the marks of each one reach.' },
      pictograma: { name: 'Pictograms', detail: 'One picture, one thing.', instruction: 'In a pictogram each picture is one thing. To know how many there are, you count the pictures in that row. The longest row is the one with most.' },
      barras: { name: 'Bar chart', detail: 'Read the length.', instruction: 'In a bar chart there are no pictures to count: you look at how far the bar reaches and read the number below. The longest bar is the one with most.' },
      tabla: { name: 'Tables', detail: 'Numbers only.', instruction: 'A table says the same as the chart, but only with numbers. You find the row and read its number.' },
      media: { name: 'Share equally', detail: 'Everyone the same.', instruction: 'Sharing equally means putting it all together and giving it out again so everyone has the same. That is what the average is.' },
      probabilidad: { name: 'Can it happen?', detail: 'Certain, it might, impossible.', instruction: 'Look at what is in the bag. If everything is that colour, taking it out is certain. If some are, it might happen. If there are none, it is impossible.' }
    },
    level: {
      y1: 'Do they go together?',
      w1: 'What is left?',
      p3: 'Drawing twice',
      k1: 'How many combinations?',
      x1: 'Which is more spread out?',
      g1: 'How many are there?',
      g2: 'Which has most?',
      g3: 'Which has least?',
      b1: 'Read the bar',
      b2: 'The longest bar',
      b3: 'The shortest bar',
      t1: 'Read the table',
      t2: 'The one that comes up most',
      a1: 'Share equally',
      p1: 'Certain, it might, impossible',
      p2: 'Which is more likely?',
      p4: 'Say the chance',
      b4: 'Two things in one chart',
      x2: 'From the lowest to the highest'
    },
    together: {
      up: 'When one goes up, so does the other',
      down: 'When one goes up, the other goes down'
    },
    cloud: {
      heightAge: { a: 'age', b: 'height' },
      studyMarks: { a: 'hours of study', b: 'the mark' },
      priceSales: { a: 'the price', b: 'how much is sold' },
      coldIceCream: { a: 'the cold', b: 'ice creams sold' }
    },
    gen: {
      scatterPrompt: '{a} and {b} have been measured. What happens?',
      scatterHint: 'Look at the dots from left to right: do they climb or fall?',
      scatterAria: 'A cloud of {n} dots.',
      afterDraw: 'You take out {thing} and do not put it back. How many of that colour are left?',
      afterHint: 'Count the ones of that colour in the bag afterwards.',
      afterAria: 'The bag before and after, with {n} of that colour at the end.',
      before: 'Before',
      after: 'After',
      howManyOutfits: 'You have {tops} tops and {bottoms} bottoms. In how many different ways can you dress?',
      outfitsHint: 'They are all drawn. Count them.',
      outfitsAria: '{n} combinations drawn.',
      whichSpread: 'Which of the two groups is more spread out?',
      whichTight: 'Which of the two groups is closer together?',
      spreadHint: 'Look at how far the marks on each row reach.',
      spreadAria: 'Two rows of marks on the same line from 1 to 10.',
      groupA: 'The top one',
      groupB: 'The bottom one',
      twoDraws: 'The bag has {n} colours. You take a ball out, put it back and take another. How many different results can come out?',
      twoDrawsHint: 'Every possible pair is drawn. Count them.',
      coinsResultAria: 'The {n} pairs that can come out.',
      howMany: 'How many {thing} are there?',
      whichMost: 'Which is there most of?',
      whichLeast: 'Which is there least of?',
      mostRepeated: 'Which one comes up most?',
      shareEqually: 'If they share it out so everyone has the same, how many does each one get?',
      shareHint: 'Put it all together and give it out again, one at a time, until everyone has the same.',
      chanceOf: 'You take a ball out of the bag without looking. Can you take out {thing}?',
      moreLikely: 'You take a ball out of the bag without looking. Which is more likely to come out?',
      moreLikelyHint: 'Whichever there is more of comes out more often.',
      bagAria: 'A bag with {n} balls.',
      whenMore: 'When was there more {a} than {b}?',
      whenSame: 'When was there the same of both things?',
      pairHint: 'Each row has two bars. Compare the top one with the one below it.',
      pairAria: 'A chart with two series: {a} and {b}.',
      rangePrompt: 'From the lowest mark to the highest one, how many steps are there?',
      rangeHint: 'Count the steps along the line from the first mark to the last one.',
      rangeAria: 'Marks on a line, from {low} to {high}.',
      chanceNumber: 'You take a ball out without looking. What is the chance it is {thing}?',
      chanceNumberHint: 'Count how many there are of that kind, and how many there are altogether.',
      outOf: '{k} out of {n}',
      countRow: 'Count the pictures in that row.',
      readScale: 'Look at how far the bar reaches and read the number below.',
      readTable: 'Find the row and read its number.',
      colThing: 'What',
      colHowMany: 'How many'
    },
    transfer: 'This will help you understand the charts that turn up in the news, on a poster at the health centre or on television.'
  }, 'en');
})();
