/* ============================================================
   Calculia — Textos de Datos y gráficos (ES)
   Archivo específico del idioma. Mismas claves que strings.en.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   Los nombres de conjuntos y categorías van en 'set.*' y 'cat.*':
   app.js los busca por el id que usa data.js, así que añadir un
   conjunto es añadir su id aquí y en los dos idiomas.
   Los números NO están aquí: viven una sola vez en data.js.
   Frases cortas, una idea por frase (UNE 153101).
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '📊 Datos y gráficos',
    instructionMenu: 'Elige una actividad.',
    contexto: 'Un gráfico cuenta de un vistazo algo que en palabras sería largo. Aparecen en las noticias, en el médico y en el súper.',
    explicacion: '✅ Leer un gráfico es mirarlo con calma y contar: quién tiene más, quién tiene menos y cuánto hay de cada cosa.',
    btnBackToMenu: '← Otras actividades',
    btnMenu: 'Volver al inicio',
    otherLevel: 'Elegir otro nivel',
    endSummary: 'Has resuelto {n} preguntas de {activity}. Ahora tienes {stars} estrellas.',
    btnHarder: '¿Quieres probar «{name}»?',
    btnOtherActivity: 'Otra actividad',
    correctExplanation: '✅ ¡Correcto! La respuesta es: ',
    incorrectExplanationA: '❌ Mira: la respuesta correcta es ',
    hint: '🤔 Prueba otra vez. Mira el gráfico con calma.',
    reinforceTitle: 'Refuerzo',
    reinforceIntro: 'Vamos a repetir las {n} preguntas que has fallado hasta acertarlas todas.',
    reinforceDone: '¡Refuerzo terminado! Ya las tienes todas.',
    chance: {
      certain: 'Seguro',
      possible: 'Puede ser',
      impossible: 'Imposible'
    },
    set: {
      fruit: 'La fruta de la cesta.',
      pets: 'Los animales de la clase.',
      weather: 'El tiempo de estos días.',
      transport: 'Cómo viene la gente.',
      drinks: 'Lo que se ha bebido hoy.',
      books: 'Los libros leídos cada día.',
      goals: 'Los goles de cada equipo.',
      visitors: 'La gente que ha venido.',
      plants: 'Las plantas de cada sitio.',
      sweets: 'Los caramelos de cada uno.',
      marbles: 'Las canicas de cada uno.',
      cards: 'Los cromos de cada uno.',
      stickers: 'Las pegatinas de cada uno.'
    },
    cat: {
      apple: 'manzanas',
      banana: 'plátanos',
      orange: 'naranjas',
      dog: 'perros',
      cat: 'gatos',
      fish: 'peces',
      sun: 'días de sol',
      rain: 'días de lluvia',
      cloud: 'días de nubes',
      bus: 'en autobús',
      bike: 'en bici',
      walk: 'andando',
      water: 'agua',
      milk: 'leche',
      juice: 'zumo',
      monday: 'el lunes',
      tuesday: 'el martes',
      wednesday: 'el miércoles',
      teamRed: 'el equipo rojo',
      teamBlue: 'el equipo azul',
      teamGreen: 'el equipo verde',
      morning: 'por la mañana',
      noon: 'al mediodía',
      evening: 'por la tarde',
      garden: 'en el jardín',
      balcony: 'en el balcón',
      window: 'en la ventana',
      ana: 'Ana',
      luis: 'Luis',
      sara: 'Sara',
      red: 'una bola roja',
      blue: 'una bola azul',
      green: 'una bola verde',
      yellow: 'una bola amarilla'
    },
    activity: {
      dosCosas: { name: 'Dos cosas a la vez', detail: 'Suben juntas o no.', instruction: 'Cuando se miden dos cosas al mismo tiempo se puede ver si van juntas. Mira la nube de puntos de izquierda a derecha: si los puntos van subiendo, cuando una sube la otra también. Si van bajando, cuando una sube la otra baja.' },
      despues: { name: 'Y después', detail: 'Lo que queda en la bolsa.', instruction: 'Si sacas una bola y no la devuelves, la siguiente vez hay una menos. Está dibujada la bolsa antes y después: cuenta lo que queda.' },
      combinaciones: { name: 'Combinaciones', detail: 'Cuántas salen.', instruction: 'Si tienes varias camisetas y varios pantalones, puedes vestirte de muchas maneras distintas. Aquí están dibujadas todas: solo hay que contarlas.' },
      reparto: { name: 'Juntos o repartidos', detail: 'Cómo están de separados.', instruction: 'Dos grupos pueden tener la misma cantidad de medidas y estar muy juntas o muy separadas. Mira de dónde a dónde llegan las marcas de cada uno.' },
      pictograma: { name: 'Pictogramas', detail: 'Un dibujo, una cosa.', instruction: 'En un pictograma cada dibujo es una cosa. Para saber cuántos hay, se cuentan los dibujos de esa fila. La fila más larga es la que más tiene.' },
      barras: { name: 'Gráfico de barras', detail: 'Leer la altura.', instruction: 'En un gráfico de barras ya no hay dibujos que contar: hay que mirar hasta dónde llega la barra y leer el número de abajo. La barra más larga es la que más tiene.' },
      tabla: { name: 'Tablas', detail: 'Solo números.', instruction: 'Una tabla dice lo mismo que el gráfico, pero solo con números. Se busca la fila y se lee su número.' },
      media: { name: 'Repartir igual', detail: 'Que todos tengan lo mismo.', instruction: 'Repartir a partes iguales es juntarlo todo y volver a darlo para que cada uno tenga lo mismo. A eso se le llama la media.' },
      probabilidad: { name: '¿Puede pasar?', detail: 'Seguro, puede ser o imposible.', instruction: 'Mira lo que hay en la bolsa. Si todo es de ese color, sacarlo es seguro. Si hay algunos, puede ser. Si no hay ninguno, es imposible.' }
    },
    level: {
      y1: '¿Suben juntas?',
      w1: '¿Qué queda?',
      p3: 'Sacar dos veces',
      k1: '¿Cuántas combinaciones?',
      x1: '¿Cuál está más repartido?',
      g1: '¿Cuántos hay?',
      g2: '¿Cuál tiene más?',
      g3: '¿Cuál tiene menos?',
      b1: 'Leer la barra',
      b2: 'La barra más larga',
      b3: 'La barra más corta',
      t1: 'Leer la tabla',
      t2: 'El que más se repite',
      a1: 'Repartir a partes iguales',
      p1: 'Seguro, puede ser o imposible',
      p2: '¿Qué es más probable?',
      p4: 'Decir la probabilidad',
      b4: 'Dos cosas en el mismo gráfico',
      x2: 'Del más bajo al más alto'
    },
    together: {
      up: 'Cuando una sube, la otra sube',
      down: 'Cuando una sube, la otra baja'
    },
    cloud: {
      heightAge: { a: 'la edad', b: 'la altura' },
      studyMarks: { a: 'las horas de estudio', b: 'la nota' },
      priceSales: { a: 'el precio', b: 'lo que se vende' },
      coldIceCream: { a: 'el frío', b: 'los helados que se venden' }
    },
    gen: {
      scatterPrompt: 'Se han medido {a} y {b}. ¿Qué pasa?',
      scatterHint: 'Mira los puntos de izquierda a derecha: ¿suben o bajan?',
      scatterAria: 'Una nube de {n} puntos.',
      afterDraw: 'Sacas {thing} y no la devuelves. ¿Cuántas quedan de ese color?',
      afterHint: 'Cuenta las de ese color en la bolsa de después.',
      afterAria: 'La bolsa antes y después, con {n} de ese color al final.',
      before: 'Antes',
      after: 'Después',
      howManyOutfits: 'Tienes {tops} prendas de arriba y {bottoms} de abajo. ¿De cuántas maneras distintas puedes vestirte?',
      outfitsHint: 'Están dibujadas todas. Cuéntalas.',
      outfitsAria: '{n} combinaciones dibujadas.',
      whichSpread: '¿Cuál de los dos grupos está más repartido?',
      whichTight: '¿Cuál de los dos grupos está más junto?',
      spreadHint: 'Mira de dónde a dónde llegan las marcas de cada fila.',
      spreadAria: 'Dos filas de marcas sobre la misma recta del 1 al 10.',
      groupA: 'El de arriba',
      groupB: 'El de abajo',
      twoDraws: 'En la bolsa hay {n} colores. Sacas una bola, la devuelves y sacas otra. ¿Cuántos resultados distintos pueden salir?',
      twoDrawsHint: 'Están dibujadas todas las parejas posibles. Cuéntalas.',
      coinsResultAria: 'Las {n} parejas que pueden salir.',
      howMany: '¿Cuántos hay de {thing}?',
      whichMost: '¿De cuál hay más?',
      whichLeast: '¿De cuál hay menos?',
      mostRepeated: '¿Cuál es el que más se repite?',
      shareEqually: 'Si lo reparten para que todos tengan lo mismo, ¿cuántos le tocan a cada uno?',
      shareHint: 'Junta todo y dalo otra vez, de uno en uno, hasta que todos tengan igual.',
      chanceOf: 'Sacas una bola de la bolsa sin mirar. ¿Puedes sacar {thing}?',
      moreLikely: 'Sacas una bola de la bolsa sin mirar. ¿Qué es más probable que salga?',
      moreLikelyHint: 'De lo que hay más, sale más veces.',
      bagAria: 'Una bolsa con {n} bolas.',
      whenMore: '¿Cuándo hubo más {a} que {b}?',
      whenSame: '¿Cuándo hubo lo mismo de las dos cosas?',
      pairHint: 'En cada fila hay dos barras. Compara la de arriba con la de abajo.',
      pairAria: 'Un gráfico con dos series: {a} y {b}.',
      rangePrompt: 'Desde la marca más baja hasta la más alta, ¿cuántos pasos hay?',
      rangeHint: 'Cuenta los pasos de la línea desde la primera marca hasta la última.',
      rangeAria: 'Marcas en una línea, desde el {low} hasta el {high}.',
      chanceNumber: 'Sacas una bola sin mirar. ¿Qué probabilidad hay de que sea {thing}?',
      chanceNumberHint: 'Cuenta cuántas hay de esa clase, y cuántas hay en total.',
      outOf: '{k} de {n}',
      countRow: 'Cuenta los dibujos de esa fila.',
      readScale: 'Mira hasta dónde llega la barra y lee el número de abajo.',
      readTable: 'Busca la fila y lee su número.',
      colThing: 'Qué',
      colHowMany: 'Cuántos'
    },
    transfer: 'Esto te servirá para entender los gráficos que salen en las noticias, en un cartel del centro de salud o en la tele.'
  }, 'es');
})();
