(function () {
  'use strict';

  App.i18n.register({
    title: '↔️ Cantidades',
    instruction: 'Mueve la barra para practicar cantidades.',
    choosePractice: 'Elige qué quieres practicar.',
    amountName: 'Poco o mucho',
    amountDetail: 'Elige una cantidad pequeña o grande.',
    changeName: 'Subir y bajar',
    changeDetail: 'Mueve una cantidad hacia arriba o abajo.',
    roundName: 'Aproximar',
    roundDetail: 'Busca la decena más cercana.',
    middleName: 'El número de en medio',
    middleDetail: 'Busca lo que queda justo en medio.',
    check: 'Comprobar',
    chooseAnother: 'Elegir otra práctica',
    roundComplete: '¡Ronda terminada!',
    roundSummary: 'Has resuelto {count} cantidades. Ahora tienes {stars} estrellas.',
    progress: '{current} de {total}',
    value: 'Ahora: {value}',
    promptAmount: 'Elige {goal}.',
    promptChange: 'Empieza en {start}. {direction} hasta {target}.',
    promptRound: 'Aproxima {value} a la decena más cercana.',
    promptMiddle: 'Entre {min} y {max}. Encuentra el número de en medio.',
    detailAmount: 'Mueve la barra. Después, comprueba.',
    detailChange: 'Mira dónde empiezas. Mueve la barra.',
    detailRound: 'Busca el número acabado en cero que está más cerca.',
    detailMiddle: 'Debe quedar la misma distancia a cada lado.',
    goalLittle: 'poco',
    goalMuch: 'mucho',
    directionIncrease: 'Sube',
    directionDecrease: 'Baja',
    hintAmount: 'Poco está cerca del principio. Mucho está cerca del final.',
    hintChange: 'Subir va hacia la derecha. Bajar va hacia la izquierda.',
    hintRound: 'Mira las dos decenas que están más cerca.',
    hintMiddle: 'Cuenta lo mismo desde cada extremo.',
    sliderLabel: 'Cantidad elegida',
    decrease: 'Bajar una cantidad',
    increase: 'Subir una cantidad',
    euro: '{value} euros',
    meter: '{value} metros',
    liter: '{value} litros',
  "contexto": "Estás midiendo o comparando cantidades del día a día: poco o mucho, más o menos, cuántos faltan.",
  "pista": "🤔 Mira el dibujo con calma. ¿Es poco o es mucho?",
  "explicacion": "✅ Así se calcula \"más o menos\". La próxima vez, prueba a pensarlo antes de medir.",
  "transferencia": "Esto te servirá para calcular cantidades reales: en la compra, en la cocina, al repartir o al medir.",
  }, 'es');
})();