(function () {
  'use strict';

  App.i18n.register({
    title: '↔️ Quantities',
    instruction: 'Move the slider to practise quantities.',
    choosePractice: 'Choose what you want to practise.',
    amountName: 'Little or much',
    amountDetail: 'Choose a small or large amount.',
    changeName: 'Increase and decrease',
    changeDetail: 'Move an amount up or down.',
    roundName: 'Round',
    roundDetail: 'Find the nearest ten.',
    middleName: 'The number in the middle',
    middleDetail: 'Find what is exactly in the middle.',
    check: 'Check',
    chooseAnother: 'Choose another practice',
    roundComplete: 'Round complete!',
    roundSummary: 'You solved {count} quantities. Now you have {stars} stars.',
    progress: '{current} of {total}',
    value: 'Now: {value}',
    promptAmount: 'Choose {goal}.',
    promptChange: 'Start at {start}. {direction} to {target}.',
    promptRound: 'Round {value} to the nearest ten.',
    promptMiddle: 'Between {min} and {max}. Find the number in the middle.',
    detailAmount: 'Move the slider. Then check.',
    detailChange: 'Look where you start. Move the slider.',
    detailRound: 'Find the number ending in zero that is closest.',
    detailMiddle: 'It must be the same distance from each end.',
    goalLittle: 'a little',
    goalMuch: 'a lot',
    directionIncrease: 'Increase',
    directionDecrease: 'Decrease',
    hintAmount: 'A little is near the beginning. A lot is near the end.',
    hintChange: 'Increasing goes right. Decreasing goes left.',
    hintRound: 'Look at the two tens that are closest.',
    hintMiddle: 'Count the same amount from each end.',
    sliderLabel: 'Chosen quantity',
    decrease: 'Decrease one amount',
    increase: 'Increase one amount',
    euro: '{value} euros',
    meter: '{value} metres',
    liter: '{value} litres',
  "contexto": "You are measuring or comparing everyday amounts: little or a lot, more or less, how many are missing.",
  "pista": "🤔 Look at the picture calmly. Is it a little or a lot?",
  "explicacion": "✅ That is how to estimate. Next time, try thinking about it before you measure.",
  "transferencia": "This will help you calculate real amounts: at the shop, in the kitchen, sharing things out or measuring.",
  }, 'en');
})();