/* ============================================================
   Calculia — Numbers texts (EN)
   Locale-specific file. Loaded conditionally from index.html
   according to App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '🧮 Numbers',
    instructionMenu: 'Maths for daily life. Choose an activity.',
    contexto: 'You are at a shop or at home. You see prices, floor numbers, change, measures and ages. Numbers help you decide.',
    explicacion: '✅ Numbers are not just for class: with them you can calculate change, know how much fruit weighs, understand a size or measure time.',
    noteTables: '🔢 For counting, adding and multiplying, open {link}.',
    notaTablasLink: 'Math Tables',
    noteTablesLink: 'Math Tables',
    notaTablas: '🔢 To count, add and multiply, go to {link}.',
    noteTables: '🔢 To count, add and multiply, go to {link}.',
    btnBackToMenu: '← Other activities',
    btnMenu: 'Back to start',
    otherLevel: 'Choose another level',
    endSummary: 'You solved {n} questions of {activity}. You now have {stars} stars.',
    btnHarder: 'Want to try «{name}»?',
    btnOtherActivity: 'Another activity',
    explicacionCorrecta: '✅ Correct! The answer is: ',
    correctExplanation: '✅ Correct! The answer is: ',
    explicacionIncorrectaA: '❌ Look: the correct answer is ',
    incorrectExplanationA: '❌ Look: the correct answer is ',
    pista: '🤔 Try again. Think calmly.',
    hint: '🤔 Try again. Think calmly.',
    refuerzoTitulo: 'Reinforcement',
    reinforceTitle: 'Reinforcement',
    refuerzoIntro: "Let's repeat the {n} questions you missed until you get them all right.",
    reinforceIntro: "Let's repeat the {n} questions you missed until you get them all right.",
    reinforceDone: "Reinforcement done! You've got them all.",
    grupoEtq: { 0: '', 1: 'thousands', 2: 'millions', 3: 'thousands of millions', 4: 'trillions' },
    groupLabel: { 0: '', 1: 'thousands', 2: 'millions', 3: 'thousands of millions', 4: 'trillions' },
    leyendaUnidadesTxt: 'ones',
    legendUnitsTxt: 'ones',
    leyendaDecenasTxt: 'tens',
    legendTensTxt: 'tens',
    leyendaCentenasTxt: 'hundreds',
    legendHundredsTxt: 'hundreds',

    hundredSingular: 'hundred',
    hundredPlural: 'hundreds',
    tenSingular: 'ten',
    tenPlural: 'tens',
    unitSingular: 'one',
    unitPlural: 'ones',
    activity: {
      'positivos-y-negativos': { name: 'Positives and negatives', detail: 'Go up and down in the elevator.', instruction: 'You have an elevator. Start at the ground floor (0). Press + to go up to upper floors (positive numbers: +1, +2, +3…). Press − to go down to lower floors (negative numbers: −1, −2, −3…). The ground floor is zero (0): not positive, not negative.' },
      unidades: { name: 'Ones and tens', detail: 'What number is it?', instruction: 'Each colour helps read the number. Blue: ones. Green: tens. Purple: hundreds.' },
      placevalue: { name: 'Changing position', detail: '10 small ones become 1 big one.', instruction: 'When you put 10 of the same together, they form 1 of the next group. The digit moves one position to the left.' },
      ordinales: { name: 'Your place in the queue', detail: 'First, second, third…', instruction: 'Ordinal numbers say which place each one is in. The queue starts at the flag 🏁. The one next to the flag is first.' },
      recta: { name: 'The number line', detail: 'Which number is the arrow pointing at?', instruction: 'Numbers go in a row, in order. The line puts them from smallest to biggest. Count from the nearest mark to find the one the arrow points at.' },
      comparar: { name: 'Greater, smaller or equal', detail: 'The signs <, > and =.', instruction: 'Look at the two numbers. The sign opens towards the bigger number. If both are the same, the sign is =.' }
    },
    ordinal: { 1: 'first', 2: 'second', 3: 'third', 4: 'fourth', 5: 'fifth' },
    ordinalPlace: { 1: 'first place', 2: 'second place', 3: 'third place', 4: 'fourth place', 5: 'fifth place' },
    level: { n1: 'Up to 10', n2: 'Up to 20', n3: 'Up to 100', n4: 'Up to 100, fewer marks', c1: 'Up to 9, with blocks', c2: 'Up to 99, with blocks', c3: 'Up to 99, no blocks', c4: 'Up to 999', c5: 'Up to 9,999', o1: 'Queue of 3', o2: 'Queue of 5', o3: 'Find a place', libre: '🛗 Free elevator', meta: '🎯 Reach a floor', u99: 'Up to 99', u999: 'Up to 999', umiles: 'Thousands', umillones: 'Millions and trillion', udictado: 'Listen and choose', counter: 'Free counter', pv1: 'Ones to tens', pv2: 'Tens to hundreds', pv3: 'Hundreds to thousands', pv4: 'Ladder of 10: up to one million', pv5: 'Ladder of 10: up to one trillion' },
    gen: {
      numberLinePrompt: 'Which number is the arrow pointing at?',
      numberLineHint: 'Count from the nearest written number.',
      numberLineAria: 'Number line from {min} to {max}.',
      compararEnunciado: 'Which sign is missing?',
      compararPista: 'The sign opens towards the bigger number.',
      compararAria: 'Compare {a} and {b}.',
      signLess: 'is smaller than',
      signGreater: 'is bigger than',
      signEqual: 'is equal to',
      ordinalPositionPrompt: 'Which place is the arrow pointing at?',
      ordinalMemberPrompt: 'Who is in {place}?',
      ordinalHint: 'Count from the flag 🏁.',
      ordinalVisualAria: 'Queue of {n}. The arrow points at place {pos}.',
      bloquesEnunciado: 'What number do the blocks make?',
      bloquesVisualAria: 'Blocks: {texto}',
      blocksPrompt: 'What number do the blocks make?',
      blocksVisualAria: 'Blocks: {texto}',
      lecturaEnunciadoNumASim: 'How do you read this number?',
      lecturaEnunciadoSimANum: 'What number is it?',
      readingNumToWordPrompt: 'How do you read this number?',
      readingWordToNumPrompt: 'What number is it?',
      canjeDirecto0: 'With {n} ones, how many tens do you make?',
      canjeDirecto1: 'With {n} tens, how many hundreds do you make?',
      canjeDirecto2: 'With {n} hundreds, how many thousands do you make?',
      canjePista0: '10 ones make 1 ten.',
      canjePista1: '10 tens make 1 hundred.',
      canjePista2: '10 hundreds make 1 thousand: 1,000.',
      canjeAriaDirecto: '{k} groups of 10 blocks',
      canjeInverso0: '{k} tens. How many ones is that?',
      canjeInverso1: '{k} hundreds. How many tens is that?',
      canjeInverso2: '{k} thousands. How many hundreds is that?',
      canjeAriaInverso: '{k} big blocks',
      carryDirect0: 'With {n} ones, how many tens do you make?',
      carryDirect1: 'With {n} tens, how many hundreds do you make?',
      carryDirect2: 'With {n} hundreds, how many thousands do you make?',
      carryReverse0: '{k} tens. How many ones is that?',
      carryReverse1: '{k} hundreds. How many tens is that?',
      carryReverse2: '{k} thousands. How many hundreds is that?',
      carryHint0: '10 ones make 1 ten.',
      carryHint1: '10 tens make 1 hundred.',
      carryHint2: '10 hundreds make 1 thousand: 1,000.',
      carryAriaDirect: '{k} groups of 10 blocks',
      carryAriaReverse: '{k} big blocks',
      escaleraEnunciado: 'How much is 10 × this number?',
      escaleraPista: 'Times 10: each digit moves one place to the left and a zero is added.',
      ladderPrompt: 'How much is 10 × this number?',
      ladderHint: 'Times 10: each digit moves one place to the left and a zero is added.',
      dictadoEnunciado: 'Read the number. Then, tap it.',
      dictationPrompt: 'Read the number. Then, tap it.',
      counterHint: 'Tap to add or subtract. Watch how the digits and the groups (ones, tens, hundreds, thousands…) change.',
      counterAudioAria: 'Read the number aloud',
      counterResetLabel: '🔄 Start at 0',
      counterExitLabel: '✅ Exit',
      counterSepOn: ',1,234',
      counterSepOff: '1234',
      counterGroupsLabel: '🎨 Colour groups',
      counterGroupsOn: '🎨 Colour groups: on',
      counterGroupsOff: '🎨 Colour groups: off',
      counterGroupsAria: 'Colour every 3-digit group',
      counterWordsOn: '✍️ Hide number in words',
      counterWordsOff: '✍️ Show number in words',
      counterWordsAria: 'Show the number written in words',
      counterResumenFinal: 'You explored the free counter. You now have {stars} stars.',
      elevatorHint: 'Press + or − to move the elevator. Watch the floor change and whether it goes up or down.',
      elevatorHintLibre: 'Press + or − to move the elevator. Watch the floor change and whether it goes up or down.',
      elevatorHintMeta: 'Press + or − until you reach the target floor. You must land on the exact floor.',
      elevatorSuggestionUp: '💡 Suggestion: go up to floor {piso}.',
      elevatorSuggestionDown: '💡 Suggestion: go down to floor {piso}.',
      elevatorReadoutAria: 'The elevator is on floor {piso}',
      elevatorStateAbove: 'Upper floor (positive number)',
      elevatorStateBelow: 'Lower floor (negative number)',
      elevatorStateGround: 'Ground floor (zero)',
      elevatorGoalMeta: 'Goal: reach floor {piso}.',
      elevatorSuccess: '🛗 You reached floor {piso}!',
      elevatorBtnReset: '🔄 Start at 0',
      elevatorBtnAudio: 'Hear the floor',
      elevatorBtnExit: '✅ Exit',
      elevatorTtsFloor: 'Floor {piso}',
      elevatorTtsAbove: 'Upper floor.',
      elevatorTtsBelow: 'Lower floor.',
      elevatorTtsGround: 'Ground floor.',
      elevatorResumenFinal: 'You explored the elevator. You now have {stars} stars.'
    },
    transfer: 'This will help you read large numbers, understand the elevator of a building, or know which digit changes when you add 100.'
  }, 'en');
})();
