/* ============================================================
   Calculia — Numbers texts (EN)
   Locale-specific file. Loaded conditionally from index.html
   according to App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '🧮 Numbers',
    instructionMenu: 'Maths for daily life. Choose an activity.',
    contexto: 'You are at a shop or at home. You see prices, floor numbers, change, measures and ages. Numbers help you decide.',
    explicacion: '✅ Numbers are not just for class: with them you can calculate change, know how much fruit weighs, understand a size or measure time.',
    noteTables: '🔢 For counting, adding and multiplying, open {link}.',
    notaTablasLink: 'Math Tables',
    noteTablesLink: 'Math Tables',
    notaTablas: '🔢 To count, add and multiply, go to {link}.',
    noteTables: '🔢 To count, add and multiply, go to {link}.',
    btnBackToMenu: '← Other activities',
    otherLevel: 'Choose another level',
    resumenFinal: 'You solved {n} questions of {actividad}. You now have {stars} stars.',
    endSummary: 'You solved {n} questions of {actividad}. You now have {stars} stars.',
    btnHarder: 'Want to try «{nombre}»?',
    btnOtherActivity: 'Another activity',
    explicacionCorrecta: '✅ Correct! The answer is: ',
    correctExplanation: '✅ Correct! The answer is: ',
    explicacionIncorrectaA: '❌ Look: the correct answer is ',
    incorrectExplanationA: '❌ Look: the correct answer is ',
    pista: '🤔 Try again. Think calmly.',
    hint: '🤔 Try again. Think calmly.',
    refuerzoTitulo: 'Reinforcement',
    reinforceTitle: 'Reinforcement',
    refuerzoIntro: "Let's repeat the {n} questions you missed until you get them all right.",
    reinforceIntro: "Let's repeat the {n} questions you missed until you get them all right.",
    reinforceDone: "Reinforcement done! You've got them all.",
    grupoEtq: { 0: '', 1: 'thousands', 2: 'millions', 3: 'thousands of millions', 4: 'trillions' },
    groupLabel: { 0: '', 1: 'thousands', 2: 'millions', 3: 'thousands of millions', 4: 'trillions' },
    leyendaUnidadesTxt: 'ones',
    legendUnitsTxt: 'ones',
    leyendaDecenasTxt: 'tens',
    legendTensTxt: 'tens',
    leyendaCentenasTxt: 'hundreds',
    legendHundredsTxt: 'hundreds',
    leyendaPlantaBajaTxt: '🏠 Ground floor = 0',
    legendGroundFloorTxt: '🏠 Ground floor = 0',
    leyendaEscalaPositivaTxt: '🔼 Upper floors = positive numbers (+)',
    legendScalePositiveTxt: '🔼 Upper floors = positive numbers (+)',
    leyendaEscalaNegativaTxt: '🔽 Lower floors = negative numbers (−)',
    legendScaleNegativeTxt: '🔽 Lower floors = negative numbers (−)',
    hundredSingular: 'hundred',
    hundredPlural: 'hundreds',
    tenSingular: 'ten',
    tenPlural: 'tens',
    unitSingular: 'one',
    unitPlural: 'ones',
    activity: {
      'positivos-y-negativos': { name: 'Positives and negatives', detail: 'Go up and down in the elevator.', instruction: 'The elevator has floors above ground and floors below. Upper floors are positive numbers (+1, +2, +3…). Lower floors are negative numbers (−1, −2, −3…). The ground floor is zero (0): not positive, not negative.' },
      unidades: { name: 'Ones and tens', detail: 'What number is it?', instruction: 'Each colour helps read the number. Blue: ones. Green: tens. Purple: hundreds.' },
      placevalue: { name: 'Changing position', detail: '10 small ones become 1 big one.', instruction: 'When you put 10 of the same together, they form 1 of the next group. The digit moves one position to the left.' }
    },
    level: { en1: 'Read the floor', en2: 'Up and down', en3: 'Which is lower?', en4: 'Find the floor', u99: 'Up to 99', u999: 'Up to 999', umiles: 'Thousands', umillones: 'Millions and trillion', udictado: 'Listen and choose', counter: 'Free counter', pv1: 'Ones to tens', pv2: 'Tens to hundreds', pv3: 'Hundreds to thousands', pv4: 'Ladder of 10: up to one million', pv5: 'Ladder of 10: up to one trillion' },
    gen: {
      ascensorLeerSituacionSuelo: 'It stays on the ground floor.',
      ascensorLeerSituacionArriba: 'Go up {n} floors.',
      ascensorLeerSituacionAbajo: 'Go down {n} floors.',
      ascensorLeerEnunciado: 'Which floor is the elevator on?',
      readFloorPrompt: 'Which floor is the elevator on?',
      onGroundFloor: 'It stays on the ground floor.',
      goUpNFloors: 'Go up {n} floors.',
      goDownNFloors: 'Go down {n} floors.',
      ascensorColocarEnunciado: 'You are on floor {inicio}. You go up {delta} floors. Which floor do you end on?',
      ascensorColocarOpcionAria: 'Letter {l}',
      moveUpPrompt: 'You are on floor {inicio}. You go up {delta} floors. Which floor do you end on?',
      moveDownPrompt: 'You are on floor {inicio}. You go down {delta} floors. Which floor do you end on?',
      compareDownPrompt: 'Which floor is lower?',
      compareUpPrompt: 'Which floor is higher?',
      placeFloorPrompt: 'Find floor {piso}. Which letter is it on?',
      placeFloorLetterAria: 'Letter {l}',
      bloquesEnunciado: 'What number do the blocks make?',
      bloquesVisualAria: 'Blocks: {texto}',
      blocksPrompt: 'What number do the blocks make?',
      blocksVisualAria: 'Blocks: {texto}',
      lecturaEnunciadoNumASim: 'How do you read this number?',
      lecturaEnunciadoSimANum: 'What number is it?',
      readingNumToWordPrompt: 'How do you read this number?',
      readingWordToNumPrompt: 'What number is it?',
      canjeDirecto0: 'With {n} ones, how many tens do you make?',
      canjeDirecto1: 'With {n} tens, how many hundreds do you make?',
      canjeDirecto2: 'With {n} hundreds, how many thousands do you make?',
      canjePista0: '10 ones make 1 ten.',
      canjePista1: '10 tens make 1 hundred.',
      canjePista2: '10 hundreds make 1 thousand: 1,000.',
      canjeAriaDirecto: '{k} groups of 10 blocks',
      canjeInverso0: '{k} tens. How many ones is that?',
      canjeInverso1: '{k} hundreds. How many tens is that?',
      canjeInverso2: '{k} thousands. How many hundreds is that?',
      canjeAriaInverso: '{k} big blocks',
      carryDirect0: 'With {n} ones, how many tens do you make?',
      carryDirect1: 'With {n} tens, how many hundreds do you make?',
      carryDirect2: 'With {n} hundreds, how many thousands do you make?',
      carryReverse0: '{k} tens. How many ones is that?',
      carryReverse1: '{k} hundreds. How many tens is that?',
      carryReverse2: '{k} thousands. How many hundreds is that?',
      carryHint0: '10 ones make 1 ten.',
      carryHint1: '10 tens make 1 hundred.',
      carryHint2: '10 hundreds make 1 thousand: 1,000.',
      carryAriaDirect: '{k} groups of 10 blocks',
      carryAriaReverse: '{k} big blocks',
      escaleraEnunciado: 'How much is 10 × this number?',
      escaleraPista: 'Times 10: each digit moves one place to the left and a zero is added.',
      ladderPrompt: 'How much is 10 × this number?',
      ladderHint: 'Times 10: each digit moves one place to the left and a zero is added.',
      dictadoEnunciado: 'Read the number. Then, tap it.',
      dictationPrompt: 'Read the number. Then, tap it.',
      counterHint: 'Tap to add or subtract. Watch how the digits and the groups (ones, tens, hundreds, thousands…) change.',
      counterAudioAria: 'Read the number aloud',
      counterResetLabel: '🔄 Start at 0',
      counterExitLabel: '✅ Exit',
      counterSepOn: ',1,234',
      counterSepOff: '1234',
      counterGroupsLabel: '🎨 Colour groups',
      counterGroupsOn: '🎨 Colour groups: on',
      counterGroupsOff: '🎨 Colour groups: off',
      counterGroupsAria: 'Colour every 3-digit group',
      counterWordsOn: '✍️ Hide number in words',
      counterWordsOff: '✍️ Show number in words',
      counterWordsAria: 'Show the number written in words',
      counterResumenFinal: 'You explored the free counter. You now have {estrellas} stars.'
    },
    transferencia: 'This will help you read large numbers, understand the elevator of a building, or know which digit changes when you add 100.',
    transfer: 'This will help you read large numbers, understand the elevator of a building, or know which digit changes when you add 100.'
  }, 'en');
})();
