/* ============================================================
   Calculia — Numbers texts (ES)
   Locale-specific file. Loaded conditionally from index.html
   according to App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '🧮 Los Números',
    instructionMenu: 'Matemáticas para el día a día. Elige una actividad.',
    contexto: 'Estás en una tienda o en casa. Ves precios, números de pisos, cambios de dinero, medidas y edades. Los números te sirven para decidir.',
    explicacion: '✅ Los números no son solo para clase: con ellos calculas el cambio, sabes cuánto pesa la fruta, entiendes una talla o mides el tiempo.',
    notaTablas: '🔢 Para contar, sumar y multiplicar, ve a {link}.',
    noteTables: '🔢 Para contar, sumar y multiplicar, ve a {link}.',
    notaTablasLink: 'Tablas',
    noteTablesLink: 'Tablas',
    btnBackToMenu: '← Otras actividades',
    btnMenu: 'Volver al inicio',
    otherLevel: 'Elegir otro nivel',
    endSummary: 'Has resuelto {n} preguntas de {activity}. Ahora tienes {stars} estrellas.',
    btnHarder: '¿Quieres probar «{name}»?',
    btnOtherActivity: 'Otra actividad',
    explicacionCorrecta: '✅ ¡Correcto! La respuesta es: ',
    correctExplanation: '✅ ¡Correcto! La respuesta es: ',
    explicacionIncorrectaA: '❌ Mira: la respuesta correcta es ',
    incorrectExplanationA: '❌ Mira: la respuesta correcta es ',
    pista: '🤔 Prueba otra vez. Piensa con calma.',
    hint: '🤔 Prueba otra vez. Piensa con calma.',
    refuerzoTitulo: 'Refuerzo',
    reinforceTitle: 'Refuerzo',
    refuerzoIntro: 'Vamos a repetir las {n} preguntas que has fallado hasta acertarlas todas.',
    reinforceIntro: 'Vamos a repetir las {n} preguntas que has fallado hasta acertarlas todas.',
    reinforceDone: '¡Refuerzo terminado! Ya las tienes todas.',
    grupoEtq: { 0: '', 1: 'miles', 2: 'millones', 3: 'millardos', 4: 'billones' },
    groupLabel: { 0: '', 1: 'miles', 2: 'millones', 3: 'millardos', 4: 'billones' },
    leyendaUnidadesTxt: 'unidades',
    legendUnitsTxt: 'unidades',
    leyendaDecenasTxt: 'decenas',
    legendTensTxt: 'decenas',
    leyendaCentenasTxt: 'centenas',
    legendHundredsTxt: 'centenas',
    hundredSingular: 'centena',
    hundredPlural: 'centenas',
    tenSingular: 'decena',
    tenPlural: 'decenas',
    unitSingular: 'unidad',
    unitPlural: 'unidades',
    activity: {
      'positivos-y-negativos': { name: 'Positivos y negativos', detail: 'Sube y baja del ascensor.', instruction: 'Tienes un ascensor. Empieza en la planta baja (0). Pulsa + para subir a pisos de arriba (números positivos: +1, +2, +3…). Pulsa − para bajar a pisos de abajo (números negativos: −1, −2, −3…). La planta baja es el cero (0): no es positivo ni negativo.' },
      unidades: { name: 'Unidades y decenas', detail: '¿Qué número es?', instruction: 'Cada color ayuda a leer el número. Azul: unidades. Verde: decenas. Morado: centenas.' },
      placevalue: { name: 'Cambiar de posición', detail: '10 pequeños se cambian por 1 grande.', instruction: 'Cuando juntas 10 iguales, forman 1 del grupo siguiente. La cifra se mueve una posición a la izquierda.' },
      ordinales: { name: 'El lugar en la fila', detail: 'Primero, segundo, tercero…', instruction: 'Los números ordinales dicen qué lugar ocupa cada uno. La fila empieza en la bandera 🏁. El de al lado de la bandera es el primero.' },
      recta: { name: 'La recta de los números', detail: '¿Qué número señala la flecha?', instruction: 'Los números van en fila y en orden. La recta los coloca de menor a mayor. Cuenta desde la marca más cercana para saber cuál señala la flecha.' },
      comparar: { name: 'Mayor, menor o igual', detail: 'Los signos <, > y =.', instruction: 'Mira los dos números. El signo se abre hacia el número más grande. Si los dos son iguales, el signo es =.' }
    },
    ordinal: { 1: 'primero', 2: 'segundo', 3: 'tercero', 4: 'cuarto', 5: 'quinto' },
    ordinalPlace: { 1: 'el primer lugar', 2: 'el segundo lugar', 3: 'el tercer lugar', 4: 'el cuarto lugar', 5: 'el quinto lugar' },
    level: { n1: 'Hasta 10', n2: 'Hasta 20', n3: 'Hasta 100', n4: 'Hasta 100, con menos marcas', c1: 'Hasta 9, con bloques', c2: 'Hasta 99, con bloques', c3: 'Hasta 99, sin bloques', c4: 'Hasta 999', c5: 'Hasta 9.999', o1: 'Fila de 3', o2: 'Fila de 5', o3: 'Buscar un lugar', libre: '🛗 Ascensor libre', meta: '🎯 Llegar a un piso', u99: 'Hasta 99', u999: 'Hasta 999', umiles: 'Los miles', umillones: 'Millones y billón', udictado: 'Escucha y elige', counter: 'Contador libre', pv1: 'De unidades a decenas', pv2: 'De decenas a centenas', pv3: 'De centenas a miles', pv4: 'Escalera del 10: hasta el millón', pv5: 'Escalera del 10: hasta el billón' },
    gen: {
      numberLinePrompt: '¿Qué número señala la flecha?',
      numberLineHint: 'Cuenta desde el número escrito más cercano.',
      numberLineAria: 'Recta numérica de {min} a {max}.',
      compararEnunciado: '¿Qué signo falta?',
      compararPista: 'El signo se abre hacia el número más grande.',
      compararAria: 'Compara {a} y {b}.',
      signLess: 'es más pequeño que',
      signGreater: 'es más grande que',
      signEqual: 'es igual a',
      ordinalPositionPrompt: '¿Qué lugar señala la flecha?',
      ordinalMemberPrompt: '¿Quién está en {place}?',
      ordinalHint: 'Cuenta desde la bandera 🏁.',
      ordinalVisualAria: 'Fila de {n}. La flecha señala el lugar {pos}.',
      bloquesEnunciado: '¿Qué número forman los bloques?',
      bloquesVisualAria: 'Bloques: {texto}',
      blocksPrompt: '¿Qué número forman los bloques?',
      blocksVisualAria: 'Bloques: {texto}',
      lecturaEnunciadoNumASim: '¿Cómo se lee este número?',
      lecturaEnunciadoSimANum: '¿Qué número es?',
      readingNumToWordPrompt: '¿Cómo se lee este número?',
      readingWordToNumPrompt: '¿Qué número es?',
      canjeDirecto0: 'Con {n} unidades, ¿cuántas decenas formas?',
      canjeDirecto1: 'Con {n} decenas, ¿cuántas centenas formas?',
      canjeDirecto2: 'Con {n} centenas, ¿cuántos miles formas?',
      canjePista0: '10 unidades forman 1 decena.',
      canjePista1: '10 decenas forman 1 centena.',
      canjePista2: '10 centenas forman 1 millar: 1.000.',
      canjeAriaDirecto: '{k} grupos de 10 bloques',
      canjeInverso0: '{k} decenas. ¿Cuántas unidades son?',
      canjeInverso1: '{k} centenas. ¿Cuántas decenas son?',
      canjeInverso2: '{k} miles. ¿Cuántas centenas son?',
      canjeAriaInverso: '{k} bloques grandes',
      carryDirect0: 'Con {n} unidades, ¿cuántas decenas formas?',
      carryDirect1: 'Con {n} decenas, ¿cuántas centenas formas?',
      carryDirect2: 'Con {n} centenas, ¿cuántos miles formas?',
      carryReverse0: '{k} decenas. ¿Cuántas unidades son?',
      carryReverse1: '{k} centenas. ¿Cuántas decenas son?',
      carryReverse2: '{k} miles. ¿Cuántas centenas son?',
      carryHint0: '10 unidades forman 1 decena.',
      carryHint1: '10 decenas forman 1 centena.',
      carryHint2: '10 centenas forman 1 millar: 1.000.',
      carryAriaDirect: '{k} grupos de 10 bloques',
      carryAriaReverse: '{k} bloques grandes',
      escaleraEnunciado: '¿Cuánto es 10 × este número?',
      escaleraPista: 'Por 10: cada cifra se mueve un sitio a la izquierda y se añade un cero.',
      ladderPrompt: '¿Cuánto es 10 × este número?',
      ladderHint: 'Por 10: cada cifra se mueve un sitio a la izquierda y se añade un cero.',
      dictadoEnunciado: 'Lee el número. Después, tócalo.',
      dictationPrompt: 'Lee el número. Después, tócalo.',
      counterHint: 'Pulsa para sumar o restar. Mira cómo cambian las cifras y los grupos (unidades, decenas, centenas, miles…).',
      counterAudioAria: 'Leer el número en voz alta',
      counterResetLabel: '🔄 Empezar en 0',
      counterExitLabel: '✅ Salir',
      counterSepOn: '·1.234',
      counterSepOff: '1234',
      counterGroupsLabel: '🎨 Colorear grupos',
      counterGroupsOn: '🎨 Colorear grupos: sí',
      counterGroupsOff: '🎨 Colorear grupos: no',
      counterGroupsAria: 'Colorear cada grupo de 3 cifras',
      counterWordsOn: '✍️ Ocultar cómo se escribe',
      counterWordsOff: '✍️ Mostrar cómo se escribe',
      counterWordsAria: 'Mostrar el número escrito con palabras',
      counterResumenFinal: 'Has explorado el contador libre. Ahora tienes {stars} estrellas.',
      elevatorHint: 'Pulsa + o − para mover el ascensor. Mira cómo cambia el piso y si sube o baja.',
      elevatorHintLibre: 'Pulsa + o − para mover el ascensor. Mira cómo cambia el piso y si sube o baja.',
      elevatorHintMeta: 'Pulsa + o − hasta llegar al piso objetivo. Tienes que acertar el piso exacto.',
      elevatorSuggestionUp: '💡 Sugerencia: sube hasta el piso {piso}.',
      elevatorSuggestionDown: '💡 Sugerencia: baja hasta el piso {piso}.',
      elevatorReadoutAria: 'El ascensor está en el piso {piso}',
      elevatorStateAbove: 'Piso de arriba (número positivo)',
      elevatorStateBelow: 'Piso de abajo (número negativo)',
      elevatorStateGround: 'Planta baja (cero)',
      elevatorGoalMeta: 'Objetivo: llegar al piso {piso}.',
      elevatorSuccess: '🛗 ¡Has llegado al piso {piso}!',
      elevatorBtnReset: '🔄 Empezar en 0',
      elevatorBtnAudio: 'Escuchar el piso',
      elevatorBtnExit: '✅ Salir',
      elevatorTtsFloor: 'Piso {piso}',
      elevatorTtsAbove: 'Piso de arriba.',
      elevatorTtsBelow: 'Piso de abajo.',
      elevatorTtsGround: 'Planta baja.',
      elevatorResumenFinal: 'Has explorado el ascensor. Ahora tienes {stars} estrellas.'
    },
    transfer: 'Esto te servirá para leer números grandes, entender el ascensor de un edificio o saber qué cifra cambia al sumar 100.'
  }, 'es');
})();
