/* ============================================================
   Calculia — Numbers texts (ES)
   Locale-specific file. Loaded conditionally from index.html
   according to App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '🧮 Los Números',
    instructionMenu: 'Matemáticas para el día a día. Elige una actividad.',
    contexto: 'Estás en una tienda o en casa. Ves precios, números de pisos, cambios de dinero, medidas y edades. Los números te sirven para decidir.',
    explicacion: '✅ Los números no son solo para clase: con ellos calculas el cambio, sabes cuánto pesa la fruta, entiendes una talla o mides el tiempo.',
    notaTablas: '🔢 Para contar, sumar y multiplicar, ve a {link}.',
    noteTables: '🔢 Para contar, sumar y multiplicar, ve a {link}.',
    notaTablasLink: 'Tablas',
    noteTablesLink: 'Tablas',
    btnBackToMenu: '← Otras actividades',
    otherLevel: 'Elegir otro nivel',
    resumenFinal: 'Has resuelto {n} preguntas de {actividad}. Ahora tienes {stars} estrellas.',
    endSummary: 'Has resuelto {n} preguntas de {actividad}. Ahora tienes {stars} estrellas.',
    btnHarder: '¿Quieres probar «{nombre}»?',
    btnOtherActivity: 'Otra actividad',
    explicacionCorrecta: '✅ ¡Correcto! La respuesta es: ',
    correctExplanation: '✅ ¡Correcto! La respuesta es: ',
    explicacionIncorrectaA: '❌ Mira: la respuesta correcta es ',
    incorrectExplanationA: '❌ Mira: la respuesta correcta es ',
    pista: '🤔 Prueba otra vez. Piensa con calma.',
    hint: '🤔 Prueba otra vez. Piensa con calma.',
    refuerzoTitulo: 'Refuerzo',
    reinforceTitle: 'Refuerzo',
    refuerzoIntro: 'Vamos a repetir las {n} preguntas que has fallado hasta acertarlas todas.',
    reinforceIntro: 'Vamos a repetir las {n} preguntas que has fallado hasta acertarlas todas.',
    reinforceDone: '¡Refuerzo terminado! Ya las tienes todas.',
    grupoEtq: { 0: '', 1: 'miles', 2: 'millones', 3: 'millardos', 4: 'billones' },
    groupLabel: { 0: '', 1: 'miles', 2: 'millones', 3: 'millardos', 4: 'billones' },
    leyendaUnidadesTxt: 'unidades',
    legendUnitsTxt: 'unidades',
    leyendaDecenasTxt: 'decenas',
    legendTensTxt: 'decenas',
    leyendaCentenasTxt: 'centenas',
    legendHundredsTxt: 'centenas',
    leyendaPlantaBajaTxt: '🏠 Planta baja = 0',
    legendGroundFloorTxt: '🏠 Planta baja = 0',
    leyendaEscalaPositivaTxt: '🔼 Pisos de arriba = números positivos (+)',
    legendScalePositiveTxt: '🔼 Pisos de arriba = números positivos (+)',
    leyendaEscalaNegativaTxt: '🔽 Pisos de abajo = números negativos (−)',
    legendScaleNegativeTxt: '🔽 Pisos de abajo = números negativos (−)',
    hundredSingular: 'centena',
    hundredPlural: 'centenas',
    tenSingular: 'decena',
    tenPlural: 'decenas',
    unitSingular: 'unidad',
    unitPlural: 'unidades',
    activity: {
      'positivos-y-negativos': { name: 'Positivos y negativos', detail: 'Sube y baja del ascensor.', instruction: 'El ascensor tiene pisos arriba y pisos bajo tierra. Los pisos de arriba son números positivos (+1, +2, +3…). Los pisos de abajo son números negativos (−1, −2, −3…). La planta baja es el cero (0): no es positivo ni negativo.' },
      unidades: { name: 'Unidades y decenas', detail: '¿Qué número es?', instruction: 'Cada color ayuda a leer el número. Azul: unidades. Verde: decenas. Morado: centenas.' },
      placevalue: { name: 'Cambiar de posición', detail: '10 pequeños se cambian por 1 grande.', instruction: 'Cuando juntas 10 iguales, forman 1 del grupo siguiente. La cifra se mueve una posición a la izquierda.' }
    },
    level: { en1: 'Leer el piso', en2: 'Subir y bajar', en3: '¿Cuál está más abajo?', en4: 'Encuentra el piso', u99: 'Hasta 99', u999: 'Hasta 999', umiles: 'Los miles', umillones: 'Millones y billón', udictado: 'Escucha y elige', pv1: 'De unidades a decenas', pv2: 'De decenas a centenas', pv3: 'De centenas a miles', pv4: 'Escalera del 10: hasta el millón', pv5: 'Escalera del 10: hasta el billón' },
    gen: {
      ascensorLeerSituacionSuelo: 'Se queda en la planta baja.',
      ascensorLeerSituacionArriba: 'Sube {n} pisos.',
      ascensorLeerSituacionAbajo: 'Baja {n} pisos.',
      ascensorLeerEnunciado: '¿En qué piso está el ascensor?',
      readFloorPrompt: '¿En qué piso está el ascensor?',
      onGroundFloor: 'Se queda en la planta baja.',
      goUpNFloors: 'Sube {n} pisos.',
      goDownNFloors: 'Baja {n} pisos.',
      ascensorColocarEnunciado: 'Estás en el piso {inicio}. Subes {delta} pisos. ¿En qué piso acabas?',
      ascensorColocarOpcionAria: 'Letra {l}',
      moveUpPrompt: 'Estás en el piso {inicio}. Subes {delta} pisos. ¿En qué piso acabas?',
      moveDownPrompt: 'Estás en el piso {inicio}. Bajas {delta} pisos. ¿En qué piso acabas?',
      compareDownPrompt: '¿Qué piso está más abajo?',
      compareUpPrompt: '¿Qué piso está más arriba?',
      placeFloorPrompt: 'Busca el piso {piso}. ¿En qué letra está?',
      placeFloorLetterAria: 'Letra {l}',
      bloquesEnunciado: '¿Qué número forman los bloques?',
      bloquesVisualAria: 'Bloques: {texto}',
      blocksPrompt: '¿Qué número forman los bloques?',
      blocksVisualAria: 'Bloques: {texto}',
      lecturaEnunciadoNumASim: '¿Cómo se lee este número?',
      lecturaEnunciadoSimANum: '¿Qué número es?',
      readingNumToWordPrompt: '¿Cómo se lee este número?',
      readingWordToNumPrompt: '¿Qué número es?',
      canjeDirecto0: 'Con {n} unidades, ¿cuántas decenas formas?',
      canjeDirecto1: 'Con {n} decenas, ¿cuántas centenas formas?',
      canjeDirecto2: 'Con {n} centenas, ¿cuántos miles formas?',
      canjePista0: '10 unidades forman 1 decena.',
      canjePista1: '10 decenas forman 1 centena.',
      canjePista2: '10 centenas forman 1 millar: 1.000.',
      canjeAriaDirecto: '{k} grupos de 10 bloques',
      canjeInverso0: '{k} decenas. ¿Cuántas unidades son?',
      canjeInverso1: '{k} centenas. ¿Cuántas decenas son?',
      canjeInverso2: '{k} miles. ¿Cuántas centenas son?',
      canjeAriaInverso: '{k} bloques grandes',
      carryDirect0: 'Con {n} unidades, ¿cuántas decenas formas?',
      carryDirect1: 'Con {n} decenas, ¿cuántas centenas formas?',
      carryDirect2: 'Con {n} centenas, ¿cuántos miles formas?',
      carryReverse0: '{k} decenas. ¿Cuántas unidades son?',
      carryReverse1: '{k} centenas. ¿Cuántas decenas son?',
      carryReverse2: '{k} miles. ¿Cuántas centenas son?',
      carryHint0: '10 unidades forman 1 decena.',
      carryHint1: '10 decenas forman 1 centena.',
      carryHint2: '10 centenas forman 1 millar: 1.000.',
      carryAriaDirect: '{k} grupos de 10 bloques',
      carryAriaReverse: '{k} bloques grandes',
      escaleraEnunciado: '¿Cuánto es 10 × este número?',
      escaleraPista: 'Por 10: cada cifra se mueve un sitio a la izquierda y se añade un cero.',
      ladderPrompt: '¿Cuánto es 10 × este número?',
      ladderHint: 'Por 10: cada cifra se mueve un sitio a la izquierda y se añade un cero.',
      dictadoEnunciado: 'Lee el número. Después, tócalo.',
      dictationPrompt: 'Lee el número. Después, tócalo.'
    },
    transferencia: 'Esto te servirá para leer números grandes, entender el ascensor de un edificio o saber qué cifra cambia al sumar 100.',
    transfer: 'Esto te servirá para leer números grandes, entender el ascensor de un edificio o saber qué cifra cambia al sumar 100.'
  }, 'es');
})();
